package ru.krindra.vknorthtypes.types.donut

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias DonutGetSubscriptionRawResponse = DonutDonatorSubscriptionInfo
@Serializable
data class DonutGetSubscriptionResponse (
    val response: DonutGetSubscriptionRawResponse
)

