package ru.krindra.vknorthtypes.types.donut

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class DonutDonatorSubscriptionInfo (
    @SerialName("next_payment_date") val nextPaymentDate: Int,
    @SerialName("status") val status: String,
    @SerialName("amount") val amount: Int,
    @SerialName("owner_id") val ownerId: Long,
)
