package ru.krindra.vknorthtypes.types.gifts

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GiftsGift (
    @SerialName("gift") val gift: GiftsLayout? = null,
    @SerialName("privacy") val privacy: GiftsGiftPrivacy? = null,
    @SerialName("id") val id: Long? = null,
    @SerialName("gift_hash") val giftHash: String? = null,
    @SerialName("date") val date: Int? = null,
    @SerialName("message") val message: String? = null,
    @SerialName("from_id") val fromId: Long? = null,
)
