package ru.krindra.vknorthtypes.types.secure

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class SecureSmsNotification (
    @SerialName("date") val date: String? = null,
    @SerialName("id") val id: String? = null,
    @SerialName("message") val message: String? = null,
    @SerialName("app_id") val appId: String? = null,
    @SerialName("user_id") val userId: String? = null,
)
