package ru.krindra.vknorthtypes.types.secure

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseBoolInt

@Serializable
data class SecureSetCounterItem (
    @SerialName("id") val id: Long,
    @SerialName("result") val result: BaseBoolInt,
)
