package ru.krindra.vknorthtypes.types.secure

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias SecureSendNotificationRawResponse = List<Int>
@Serializable
data class SecureSendNotificationResponse (
    val response: SecureSendNotificationRawResponse
)

