package ru.krindra.vknorthtypes.types.secure

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class SecureTokenChecked (
    @SerialName("user_id") val userId: Long? = null,
    @SerialName("expire") val expire: Int? = null,
    @SerialName("date") val date: Int? = null,
    @SerialName("success") val success: Int? = null,
)
