package ru.krindra.vknorthtypes.types.secure

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias SecureSetCounterArrayRawResponse = List<SecureSetCounterItem>
@Serializable
data class SecureSetCounterArrayResponse (
    val response: SecureSetCounterArrayRawResponse
)

