package ru.krindra.vknorthtypes.types.secure

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class SecureLevel (
    @SerialName("level") val level: Int? = null,
    @SerialName("uid") val uid: Long? = null,
)
