package ru.krindra.vknorthtypes.types.utils

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias UtilsGetServerTimeRawResponse = Int
/**
 *
 * Time as Unixtime
 * 
 */
@Serializable
data class UtilsGetServerTimeResponse (
    val response: UtilsGetServerTimeRawResponse
)

