package ru.krindra.vknorthtypes.types.utils

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class UtilsStatsSexAge (
    @SerialName("male") val male: Int? = null,
    @SerialName("female") val female: Int? = null,
    @SerialName("age_range") val ageRange: String? = null,
)
