package ru.krindra.vknorthtypes.types.utils

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias UtilsGetLinkStatsExtendedRawResponse = UtilsLinkStatsExtended
@Serializable
data class UtilsGetLinkStatsExtendedResponse (
    val response: UtilsGetLinkStatsExtendedRawResponse
)

