package ru.krindra.vknorthtypes.types.utils

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class UtilsLinkStats (
    @SerialName("stats") val stats: List<UtilsStats>? = null,
    @SerialName("key") val key: String? = null,
)
