package ru.krindra.vknorthtypes.types.utils

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class UtilsLastShortenedLink (
    @SerialName("short_url") val shortUrl: String? = null,
    @SerialName("url") val url: String? = null,
    @SerialName("key") val key: String? = null,
    @SerialName("views") val views: Int? = null,
    @SerialName("timestamp") val timestamp: Int? = null,
    @SerialName("access_key") val accessKey: String? = null,
)
