package ru.krindra.vknorthtypes.types.streaming

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class StreamingGetStemResponse (
    val response: StreamingGetStemRawResponse
) {
    /**
     *
     * @param stem part of a word responsible for its lexical meaning
     */
    @Serializable
    data class StreamingGetStemRawResponse (
        @SerialName("stem") val stem: String? = null,
    )
}

