package ru.krindra.vknorthtypes.types.streaming

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias StreamingGetStatsRawResponse = List<StreamingStats>
@Serializable
data class StreamingGetStatsResponse (
    val response: StreamingGetStatsRawResponse
)

