package ru.krindra.vknorthtypes.types.streaming

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class StreamingGetStemResponse (
    val response: StreamingGetStemRawResponse
) {
    @Serializable
    data class StreamingGetStemRawResponse (
        @SerialName("stem") val stem: String? = null,
    )
}

