package ru.krindra.vknorthtypes.types.streaming

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class StreamingGetServerUrlResponse (
    val response: StreamingGetServerUrlRawResponse
) {
    /**
     *
     * @param endpoint Server host
     * @param key Access key
     */
    @Serializable
    data class StreamingGetServerUrlRawResponse (
        @SerialName("endpoint") val endpoint: String? = null,
        @SerialName("key") val key: String? = null,
    )
}

