package ru.krindra.vknorthtypes.types.adsweb

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AdswebGetAdUnitCodeResponse (
    val response: AdswebGetAdUnitCodeRawResponse
) {
    /**
     *
     * @param html 
     */
    @Serializable
    data class AdswebGetAdUnitCodeRawResponse (
        @SerialName("html") val html: String,
    )
}

