package ru.krindra.vknorthtypes.types.adsweb

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AdswebGetAdCategoriesResponse (
    val response: AdswebGetAdCategoriesRawResponse
) {
    @Serializable
    data class AdswebGetAdCategoriesRawResponse (
        @SerialName("categories") val categories: List<AdswebGetAdCategoriesResponseCategoriesCategory>,
    )
}

