package ru.krindra.vknorthtypes.types.adsweb

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param id 
 * @param statusUser 
 * @param statusModer 
 * @param domains 
 */
@Serializable
data class AdswebGetSitesResponseSitesSite (
    @SerialName("status_moder") val statusModer: String? = null,
    @SerialName("status_user") val statusUser: String? = null,
    @SerialName("domains") val domains: String? = null,
    @SerialName("id") val id: Long,
)
