package ru.krindra.vknorthtypes.types.adsweb

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AdswebGetAdUnitsResponseAdUnitsAdUnit (
    @SerialName("id") val id: Long,
    @SerialName("site_id") val siteId: Long,
    @SerialName("name") val name: String? = null,
)
