package ru.krindra.vknorthtypes.types.adsweb

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param id 
 * @param name 
 */
@Serializable
data class AdswebGetAdCategoriesResponseCategoriesCategory (
    @SerialName("name") val name: String,
    @SerialName("id") val id: Long,
)
