package ru.krindra.vknorthtypes.types.audio

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AudioAudio (
    @SerialName("id") val id: Long,
    @SerialName("artist") val artist: String,
    @SerialName("owner_id") val ownerId: Long,
    @SerialName("title") val title: String,
    @SerialName("url") val url: String? = null,
    @SerialName("date") val date: Int? = null,
    @SerialName("album_id") val albumId: Long? = null,
    @SerialName("performer") val performer: String? = null,
    @SerialName("access_key") val accessKey: String? = null,
    @SerialName("duration") val duration: Int,
)
