package ru.krindra.vknorthtypes.types.apps

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseBoolInt

@Serializable
data class AppsApp (
    @SerialName("international") val international: Boolean? = null,
    @SerialName("icon_139") val icon139: String? = null,
    @SerialName("friends") val friends: List<Int>? = null,
    @SerialName("author_owner_id") val authorOwnerId: Long? = null,
    @SerialName("title") val title: String,
    @SerialName("loader_icon") val loaderIcon: String? = null,
    @SerialName("screen_orientation") val screenOrientation: Int? = null,
    @SerialName("genre_id") val genreId: Long? = null,
    @SerialName("platform_id") val platformId: String? = null,
    @SerialName("banner_1120") val banner1120: String? = null,
    @SerialName("published_date") val publishedDate: Int? = null,
    @SerialName("icon_150") val icon150: String? = null,
    @SerialName("screen_name") val screenName: String? = null,
    @SerialName("push_enabled") val pushEnabled: BaseBoolInt? = null,
    @SerialName("description") val description: String? = null,
    @SerialName("is_installed") val isInstalled: Boolean? = null,
    @SerialName("members_count") val membersCount: Int? = null,
    @SerialName("icon_278") val icon278: String? = null,
    @SerialName("background_loader_color") val backgroundLoaderColor: String? = null,
    @SerialName("icon_16") val icon16: String? = null,
    @SerialName("genre") val genre: String? = null,
    @SerialName("is_in_catalog") val isInCatalog: Int? = null,
    @SerialName("is_new") val isNew: BaseBoolInt? = null,
    @SerialName("catalog_position") val catalogPosition: Int? = null,
    @SerialName("leaderboard_type") val leaderboardType: AppsAppLeaderboardType? = null,
    @SerialName("id") val id: Long,
    @SerialName("banner_560") val banner560: String? = null,
    @SerialName("icon_576") val icon576: String? = null,
    @SerialName("icon_75") val icon75: String? = null,
    @SerialName("section") val section: String? = null,
    @SerialName("type") val type: AppsAppType,
    @SerialName("author_url") val authorUrl: String? = null,
)
