package ru.krindra.vknorthtypes.types.apps

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AppsGetLastUploadedVersionResponse (
    val response: AppsGetLastUploadedVersionRawResponse
) {
    /**
     *
     * @param version Last uploaded version
     */
    @Serializable
    data class AppsGetLastUploadedVersionRawResponse (
        @SerialName("version") val version: String,
    )
}

