package ru.krindra.vknorthtypes.types.apps

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.users.UsersUserFull


@Serializable
data class AppsGetFriendsListExtendedResponse (
    val response: AppsGetFriendsListExtendedRawResponse
) {
    /**
     *
     * @param count Total number
     * @param items 
     */
    @Serializable
    data class AppsGetFriendsListExtendedRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<UsersUserFull>,
    )
}

