package ru.krindra.vknorthtypes.types.apps

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AppsGetTestingGroupsRawResponse = List<AppsTestingGroup>
@Serializable
data class AppsGetTestingGroupsResponse (
    val response: AppsGetTestingGroupsRawResponse
)

