package ru.krindra.vknorthtypes.types.apps

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.users.UsersUserMin

/**
 *
 * @param count Total number
 * @param items 
 * @param profiles 
 */
@Serializable
data class AppsCatalogList (
    @SerialName("profiles") val profiles: List<UsersUserMin>? = null,
    @SerialName("count") val count: Int,
    @SerialName("items") val items: List<AppsApp>,
)
