package ru.krindra.vknorthtypes.types.apps

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AppsIsNotificationsAllowedResponse (
    val response: AppsIsNotificationsAllowedRawResponse
) {
    @Serializable
    data class AppsIsNotificationsAllowedRawResponse (
        @SerialName("is_allowed") val isAllowed: Boolean,
    )
}

