package ru.krindra.vknorthtypes.types.apps

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AppsCreatedGroupResponse (
    val response: AppsCreatedGroupRawResponse
) {
    /**
     *
     * @param groupId 
     */
    @Serializable
    data class AppsCreatedGroupRawResponse (
        @SerialName("group_id") val groupId: Long,
    )
}

