package ru.krindra.vknorthtypes.types.apps

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * Scope description
 * 
 * @param name Scope name
 * @param title Scope title
 */
@Serializable
data class AppsScope (
    @SerialName("name") val name: String,
    @SerialName("title") val title: String? = null,
)
