package ru.krindra.vknorthtypes.types.apps

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AppsImageUploadResponse (
    val response: AppsImageUploadRawResponse
) {
    /**
     *
     * @param hash Uploading hash
     * @param image Uploaded photo data
     */
    @Serializable
    data class AppsImageUploadRawResponse (
        @SerialName("hash") val hash: String? = null,
        @SerialName("image") val image: String? = null,
    )
}

