package ru.krindra.vknorthtypes.types.apps

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AppsGetScoreRawResponse = Int
/**
 *
 * Score number
 * 
 */
@Serializable
data class AppsGetScoreResponse (
    val response: AppsGetScoreRawResponse
)

