package ru.krindra.vknorthtypes.types.apps

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AppsGetScopesResponse (
    val response: AppsGetScopesRawResponse
) {
    /**
     *
     * @param count Total number
     * @param items 
     */
    @Serializable
    data class AppsGetScopesRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<AppsScope>,
    )
}

