package ru.krindra.vknorthtypes.types.events

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.groups.GroupsGroupFullMemberStatus

@Serializable
data class EventsEventAttach (
    @SerialName("button_text") val buttonText: String,
    @SerialName("id") val id: Long,
    @SerialName("is_favorite") val isFavorite: Boolean,
    @SerialName("address") val address: String? = null,
    @SerialName("member_status") val memberStatus: GroupsGroupFullMemberStatus? = null,
    @SerialName("text") val text: String,
    @SerialName("time") val time: Int? = null,
    @SerialName("friends") val friends: List<Int>,
)
