package ru.krindra.vknorthtypes.types.video

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class VideoStartStreamingResponse (
    val response: VideoStartStreamingRawResponse
) {
    @Serializable
    data class VideoStartStreamingRawResponse (
        @SerialName("owner_id") val ownerId: Long,
        @SerialName("video_id") val videoId: Long,
        @SerialName("name") val name: String,
        @SerialName("description") val description: String,
        @SerialName("access_key") val accessKey: String,
        @SerialName("stream") val stream: VideoStreamInputParams,
        @SerialName("post_id") val postId: Long? = null,
    )
}

