package ru.krindra.vknorthtypes.types.video

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class VideoGetAlbumsResponse (
    val response: VideoGetAlbumsRawResponse
) {
    /**
     *
     * @param count Total number
     * @param items 
     */
    @Serializable
    data class VideoGetAlbumsRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<VideoVideoAlbum>,
    )
}

