package ru.krindra.vknorthtypes.types.video

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BasePropertyExists

@Serializable
data class VideoVideoImage (
    @SerialName("id") val id: String? = null,
    @SerialName("theme") val theme: String? = null,
    @SerialName("width") val width: Int,
    @SerialName("height") val height: Int,
    @SerialName("with_padding") val withPadding: BasePropertyExists? = null,
    @SerialName("url") val url: String,
)
