package ru.krindra.vknorthtypes.types.video

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias VideoLiveGetCategoriesRawResponse = List<VideoLiveCategory>
@Serializable
data class VideoLiveGetCategoriesResponse (
    val response: VideoLiveGetCategoriesRawResponse
)

