package ru.krindra.vknorthtypes.types.callback

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class CallbackMarketComment (
    @SerialName("id") val id: Long,
    @SerialName("photo_id") val photoId: Long? = null,
    @SerialName("market_owner_id") val marketOwnerId: Long? = null,
    @SerialName("date") val date: Int,
    @SerialName("text") val text: String? = null,
    @SerialName("from_id") val fromId: Long,
)
