package ru.krindra.vknorthtypes.types.callback

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param likerId 
 * @param objectType 
 * @param objectOwnerId 
 * @param objectId 
 * @param postId 
 * @param threadReplyId 
 */
@Serializable
data class CallbackLikeAddRemove (
    @SerialName("object_owner_id") val objectOwnerId: Long,
    @SerialName("thread_reply_id") val threadReplyId: Long? = null,
    @SerialName("object_type") val objectType: String,
    @SerialName("liker_id") val likerId: Long,
    @SerialName("post_id") val postId: Long,
    @SerialName("object_id") val objectId: Long,
)
