package ru.krindra.vknorthtypes.types.callback

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class CallbackDonutSubscriptionPriceChanged (
    @SerialName("amount_diff") val amountDiff: Double? = null,
    @SerialName("amount_diff_without_fee") val amountDiffWithoutFee: Double? = null,
    @SerialName("amount_old") val amountOld: Int,
    @SerialName("user_id") val userId: Long? = null,
    @SerialName("amount_new") val amountNew: Int,
)
