package ru.krindra.vknorthtypes.types.callback

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class CallbackGroupOfficersEdit (
    @SerialName("level_new") val levelNew: CallbackGroupOfficerRole,
    @SerialName("level_old") val levelOld: CallbackGroupOfficerRole,
    @SerialName("admin_id") val adminId: Long,
    @SerialName("user_id") val userId: Long,
)
