package ru.krindra.vknorthtypes.types.callback

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param adminId 
 * @param userId 
 * @param levelOld 
 * @param levelNew 
 */
@Serializable
data class CallbackGroupOfficersEdit (
    @SerialName("level_new") val levelNew: CallbackGroupOfficerRole,
    @SerialName("user_id") val userId: Long,
    @SerialName("admin_id") val adminId: Long,
    @SerialName("level_old") val levelOld: CallbackGroupOfficerRole,
)
