package ru.krindra.vknorthtypes.types.callback

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class CallbackBoardPostDelete (
    @SerialName("id") val id: Long,
    @SerialName("topic_owner_id") val topicOwnerId: Long,
    @SerialName("topic_id") val topicId: Long,
)
