package ru.krindra.vknorthtypes.types.callback

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class CallbackType(val value: String){
    @SerialName("audio_new") AUDIO_NEW("audio_new"),
    @SerialName("board_post_new") BOARD_POST_NEW("board_post_new"),
    @SerialName("board_post_edit") BOARD_POST_EDIT("board_post_edit"),
    @SerialName("board_post_restore") BOARD_POST_RESTORE("board_post_restore"),
    @SerialName("board_post_delete") BOARD_POST_DELETE("board_post_delete"),
    @SerialName("confirmation") CONFIRMATION("confirmation"),
    @SerialName("group_leave") GROUP_LEAVE("group_leave"),
    @SerialName("group_join") GROUP_JOIN("group_join"),
    @SerialName("group_change_photo") GROUP_CHANGE_PHOTO("group_change_photo"),
    @SerialName("group_change_settings") GROUP_CHANGE_SETTINGS("group_change_settings"),
    @SerialName("group_officers_edit") GROUP_OFFICERS_EDIT("group_officers_edit"),
    @SerialName("lead_forms_new") LEAD_FORMS_NEW("lead_forms_new"),
    @SerialName("market_comment_new") MARKET_COMMENT_NEW("market_comment_new"),
    @SerialName("market_comment_delete") MARKET_COMMENT_DELETE("market_comment_delete"),
    @SerialName("market_comment_edit") MARKET_COMMENT_EDIT("market_comment_edit"),
    @SerialName("market_comment_restore") MARKET_COMMENT_RESTORE("market_comment_restore"),
    @SerialName("market_order_new") MARKET_ORDER_NEW("market_order_new"),
    @SerialName("market_order_edit") MARKET_ORDER_EDIT("market_order_edit"),
    @SerialName("message_new") MESSAGE_NEW("message_new"),
    @SerialName("message_reply") MESSAGE_REPLY("message_reply"),
    @SerialName("message_edit") MESSAGE_EDIT("message_edit"),
    @SerialName("message_allow") MESSAGE_ALLOW("message_allow"),
    @SerialName("message_deny") MESSAGE_DENY("message_deny"),
    @SerialName("message_read") MESSAGE_READ("message_read"),
    @SerialName("message_typing_state") MESSAGE_TYPING_STATE("message_typing_state"),
    @SerialName("messages_edit") MESSAGES_EDIT("messages_edit"),
    @SerialName("message_reaction_event") MESSAGE_REACTION_EVENT("message_reaction_event"),
    @SerialName("photo_new") PHOTO_NEW("photo_new"),
    @SerialName("photo_comment_new") PHOTO_COMMENT_NEW("photo_comment_new"),
    @SerialName("photo_comment_delete") PHOTO_COMMENT_DELETE("photo_comment_delete"),
    @SerialName("photo_comment_edit") PHOTO_COMMENT_EDIT("photo_comment_edit"),
    @SerialName("photo_comment_restore") PHOTO_COMMENT_RESTORE("photo_comment_restore"),
    @SerialName("poll_vote_new") POLL_VOTE_NEW("poll_vote_new"),
    @SerialName("user_block") USER_BLOCK("user_block"),
    @SerialName("user_unblock") USER_UNBLOCK("user_unblock"),
    @SerialName("video_new") VIDEO_NEW("video_new"),
    @SerialName("video_comment_new") VIDEO_COMMENT_NEW("video_comment_new"),
    @SerialName("video_comment_delete") VIDEO_COMMENT_DELETE("video_comment_delete"),
    @SerialName("video_comment_edit") VIDEO_COMMENT_EDIT("video_comment_edit"),
    @SerialName("video_comment_restore") VIDEO_COMMENT_RESTORE("video_comment_restore"),
    @SerialName("wall_post_new") WALL_POST_NEW("wall_post_new"),
    @SerialName("wall_reply_new") WALL_REPLY_NEW("wall_reply_new"),
    @SerialName("wall_reply_edit") WALL_REPLY_EDIT("wall_reply_edit"),
    @SerialName("wall_reply_delete") WALL_REPLY_DELETE("wall_reply_delete"),
    @SerialName("wall_reply_restore") WALL_REPLY_RESTORE("wall_reply_restore"),
    @SerialName("wall_repost") WALL_REPOST("wall_repost"),
}
