package ru.krindra.vknorthtypes.types.callback

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.photos.PhotosPhoto

@Serializable
data class CallbackGroupChangePhoto (
    @SerialName("photo") val photo: PhotosPhoto,
    @SerialName("user_id") val userId: Long,
)
