package ru.krindra.vknorthtypes.types.callback

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param type 
 * @param object_ 
 * @param groupId 
 * @param eventId Unique event id. If it passed twice or more - you should ignore it.
 * @param v API object version
 * @param secret 
 */
@Serializable
data class CallbackMessageAllow (
    @SerialName("type") val type: CallbackType? = null,
    @SerialName("event_id") val eventId: String,
    @SerialName("object_") val object_: CallbackMessageAllowObject,
    @SerialName("secret") val secret: String? = null,
    @SerialName("v") val v: String,
    @SerialName("group_id") val groupId: Long,
)
