package ru.krindra.vknorthtypes.types.callback

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param adminId 
 * @param userId 
 * @param unblockDate 
 * @param reason 
 * @param comment 
 */
@Serializable
data class CallbackUserBlock (
    @SerialName("admin_id") val adminId: Long,
    @SerialName("reason") val reason: Int,
    @SerialName("unblock_date") val unblockDate: Int,
    @SerialName("comment") val comment: String? = null,
    @SerialName("user_id") val userId: Long,
)
