package ru.krindra.vknorthtypes.types.base

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class BaseLikesInfo (
    @SerialName("count") val count: Int,
    @SerialName("repost_disabled") val repostDisabled: Boolean? = null,
    @SerialName("user_likes") val userLikes: BaseBoolInt,
    @SerialName("can_publish") val canPublish: BaseBoolInt? = null,
    @SerialName("can_like") val canLike: BaseBoolInt,
)
