package ru.krindra.vknorthtypes.types.base

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class BasePlace (
    @SerialName("longitude") val longitude: Double? = null,
    @SerialName("address") val address: String? = null,
    @SerialName("latitude") val latitude: Double? = null,
    @SerialName("created") val created: Int? = null,
    @SerialName("id") val id: Long? = null,
    @SerialName("icon") val icon: String? = null,
    @SerialName("title") val title: String? = null,
    @SerialName("checkins") val checkins: Int? = null,
    @SerialName("country") val country: String? = null,
    @SerialName("city") val city: String? = null,
    @SerialName("type") val type: String? = null,
)
