package ru.krindra.vknorthtypes.types.base

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class BaseOwnerCover (
    @SerialName("images") val images: List<BaseImage>? = null,
    @SerialName("enabled") val enabled: BaseBoolInt,
    @SerialName("crop_params") val cropParams: BaseOwnerCoverCropParams? = null,
    @SerialName("original_image") val originalImage: BaseImage? = null,
    @SerialName("photo_id") val photoId: Long? = null,
)
