package ru.krindra.vknorthtypes.types.base

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.wall.WallWallComment
import ru.krindra.vknorthtypes.types.wall.WallWallpostCommentsDonut

@Serializable
data class BaseCommentsInfo (
    @SerialName("donut") val donut: WallWallpostCommentsDonut? = null,
    @SerialName("groups_can_post") val groupsCanPost: Boolean? = null,
    @SerialName("can_open") val canOpen: BaseBoolInt? = null,
    @SerialName("can_view") val canView: BaseBoolInt? = null,
    @SerialName("count") val count: Int? = null,
    @SerialName("list") val list: List<WallWallComment>? = null,
    @SerialName("can_post") val canPost: BaseBoolInt? = null,
    @SerialName("can_close") val canClose: BaseBoolInt? = null,
)
