package ru.krindra.vknorthtypes.types.base

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias BaseOkRawResponse = Int
@Serializable
data class BaseOkResponse (
    val response: BaseOkRawResponse
)

