package ru.krindra.vknorthtypes.types.base

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias BaseGetUploadServerRawResponse = BaseUploadServer
@Serializable
data class BaseGetUploadServerResponse (
    val response: BaseGetUploadServerRawResponse
)

