package ru.krindra.vknorthtypes.types.base

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class BaseStickerNew (
    @SerialName("images") val images: List<BaseImage>? = null,
    @SerialName("is_allowed") val isAllowed: Boolean? = null,
    @SerialName("images_with_background") val imagesWithBackground: List<BaseImage>? = null,
    @SerialName("animation_url") val animationUrl: String? = null,
    @SerialName("animations") val animations: List<BaseStickerAnimation>? = null,
    @SerialName("product_id") val productId: Long? = null,
    @SerialName("sticker_id") val stickerId: Long? = null,
)
