package ru.krindra.vknorthtypes.types.base

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class BaseError (
    @SerialName("request_params") val requestParams: List<BaseRequestParam>? = null,
    @SerialName("error_subcode") val errorSubcode: Int? = null,
    @SerialName("error_msg") val errorMsg: String? = null,
    @SerialName("error_text") val errorText: String? = null,
    @SerialName("error_code") val errorCode: Int,
)
