package ru.krindra.vknorthtypes.types.fave

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.market.MarketMarketItem
import ru.krindra.vknorthtypes.types.base.BaseLink
import ru.krindra.vknorthtypes.types.video.VideoVideoFull
import ru.krindra.vknorthtypes.types.wall.WallWallpostFull

/**
 *
 * @param addedDate Timestamp, when this item was bookmarked
 * @param link 
 * @param post 
 * @param product 
 * @param seen Has user seen this item
 * @param tags 
 * @param type Item type
 * @param video 
 */
@Serializable
data class FaveBookmark (
    @SerialName("post") val post: WallWallpostFull? = null,
    @SerialName("link") val link: BaseLink? = null,
    @SerialName("added_date") val addedDate: Int,
    @SerialName("seen") val seen: Boolean,
    @SerialName("product") val product: MarketMarketItem? = null,
    @SerialName("tags") val tags: List<FaveTag>,
    @SerialName("video") val video: VideoVideoFull? = null,
    @SerialName("type") val type: FaveBookmarkType,
)
