package ru.krindra.vknorthtypes.types.fave

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.users.UsersUserFull
import ru.krindra.vknorthtypes.types.groups.GroupsGroupFull

/**
 *
 * @param description Some info about user or group
 * @param group 
 * @param tags 
 * @param type Item type
 * @param updatedDate Timestamp, when this page was bookmarked
 * @param user 
 */
@Serializable
data class FavePage (
    @SerialName("updated_date") val updatedDate: Int? = null,
    @SerialName("type") val type: FavePageType,
    @SerialName("group") val group: GroupsGroupFull? = null,
    @SerialName("tags") val tags: List<FaveTag>,
    @SerialName("user") val user: UsersUserFull? = null,
    @SerialName("description") val description: String,
)
