package ru.krindra.vknorthtypes.types.fave

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias FaveAddTagRawResponse = FaveTag
@Serializable
data class FaveAddTagResponse (
    val response: FaveAddTagRawResponse
)

