package ru.krindra.vknorthtypes.types.board

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.polls.PollsPoll


@Serializable
data class BoardGetCommentsResponse (
    val response: BoardGetCommentsRawResponse
) {
    /**
     *
     * @param count Total number
     * @param items 
     * @param poll 
     * @param realOffset Offset of comment
     */
    @Serializable
    data class BoardGetCommentsRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<BoardTopicComment>,
        @SerialName("poll") val poll: PollsPoll? = null,
        @SerialName("real_offset") val realOffset: Int? = null,
    )
}

