package ru.krindra.vknorthtypes.types.board

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias BoardCreateCommentRawResponse = Int
@Serializable()
data class BoardCreateCommentResponse (
    val response: BoardCreateCommentRawResponse
)

