package ru.krindra.vknorthtypes.types.board

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias BoardAddTopicRawResponse = Int
/**
 *
 * Topic ID
 * 
 */
@Serializable
data class BoardAddTopicResponse (
    val response: BoardAddTopicRawResponse
)

