package ru.krindra.vknorthtypes.types.board

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseBoolInt
import ru.krindra.vknorthtypes.types.wall.WallCommentAttachment
import ru.krindra.vknorthtypes.types.base.BaseLikesInfo

@Serializable
data class BoardTopicComment (
    @SerialName("id") val id: Long,
    @SerialName("date") val date: Int,
    @SerialName("likes") val likes: BaseLikesInfo? = null,
    @SerialName("real_offset") val realOffset: Int? = null,
    @SerialName("can_edit") val canEdit: BaseBoolInt? = null,
    @SerialName("text") val text: String,
    @SerialName("attachments") val attachments: List<WallCommentAttachment>? = null,
    @SerialName("from_id") val fromId: Long,
)
