package ru.krindra.vknorthtypes.types.board

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.groups.GroupsGroupFull

import ru.krindra.vknorthtypes.types.users.UsersUserFull

import ru.krindra.vknorthtypes.types.base.BaseBoolInt


@Serializable
data class BoardGetTopicsExtendedResponse (
    val response: BoardGetTopicsExtendedRawResponse
) {
    @Serializable
    data class BoardGetTopicsExtendedRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<BoardTopic>,
        @SerialName("default_order") val defaultOrder: BoardDefaultOrder,
        @SerialName("can_add_topics") val canAddTopics: BaseBoolInt,
        @SerialName("profiles") val profiles: List<UsersUserFull>,
        @SerialName("groups") val groups: List<GroupsGroupFull>,
    )
}

