package ru.krindra.vknorthtypes.types.appWidgets

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AppWidgetsSaveAppImageRawResponse = AppWidgetsPhoto
@Serializable
data class AppWidgetsSaveAppImageResponse (
    val response: AppWidgetsSaveAppImageRawResponse
)

