package ru.krindra.vknorthtypes.types.appWidgets

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param count 
 * @param items 
 */
@Serializable
data class AppWidgetsPhotos (
    @SerialName("items") val items: List<AppWidgetsPhoto>? = null,
    @SerialName("count") val count: Int? = null,
)
