package ru.krindra.vknorthtypes.types.appWidgets

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AppWidgetsGetAppImagesRawResponse = AppWidgetsPhotos
@Serializable
data class AppWidgetsGetAppImagesResponse (
    val response: AppWidgetsGetAppImagesRawResponse
)

