package ru.krindra.vknorthtypes.types.appWidgets

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AppWidgetsGetGroupImagesRawResponse = AppWidgetsPhotos
@Serializable
data class AppWidgetsGetGroupImagesResponse (
    val response: AppWidgetsGetGroupImagesRawResponse
)

