package ru.krindra.vknorthtypes.types.stickers

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseImage

@Serializable
data class StickersImageSet (
    @SerialName("base_url") val baseUrl: String,
    @SerialName("version") val version: Int? = null,
    @SerialName("images") val images: List<BaseImage>? = null,
)
