package ru.krindra.vknorthtypes.types.support

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class SupportUnblockScreenModalButtonFields (
    @SerialName("type") val type: String,
    @SerialName("id") val id: Double? = null,
    @SerialName("modal") val modal: SupportUnblockScreenModalButtonModalContent? = null,
    @SerialName("label") val label: String? = null,
)
