package ru.krindra.vknorthtypes.types.support

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class SupportUnblockScreenStepperQuestions (
    @SerialName("yes_desc") val yesDesc: String? = null,
    @SerialName("title") val title: String,
    @SerialName("step") val step: Double? = null,
    @SerialName("no_desc") val noDesc: String? = null,
    @SerialName("target_screen") val targetScreen: String,
)
