package ru.krindra.vknorthtypes.types.support

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class SupportUnblockScreenSlidersFields (
    @SerialName("type") val type: String,
    @SerialName("items") val items: List<SupportUnblockScreenSlidersFieldsItem>? = null,
)
