package ru.krindra.vknorthtypes.types.support

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class SupportUnblockScreenModalButtonModalContent (
    @SerialName("text") val text: String? = null,
    @SerialName("title") val title: String? = null,
)
