package ru.krindra.vknorthtypes.types.support

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class SupportUnblockScreenTutorialQuestions (
    @SerialName("title") val title: String? = null,
    @SerialName("answers") val answers: List<SupportUnblockScreenTutorialAnswers>? = null,
    @SerialName("id") val id: String? = null,
)
