package ru.krindra.vknorthtypes.types.support

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class SupportUnblockScreenStepperFields (
    @SerialName("type") val type: String,
    @SerialName("questions") val questions: List<SupportUnblockScreenStepperQuestions>? = null,
    @SerialName("target") val target: String? = null,
)
