package ru.krindra.vknorthtypes.types.orders

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param amounts 
 * @param currency Currency name
 */
@Serializable
data class OrdersAmount (
    @SerialName("amounts") val amounts: List<OrdersAmountItem>? = null,
    @SerialName("currency") val currency: String? = null,
)
