package ru.krindra.vknorthtypes.types.orders

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class OrdersAmount (
    @SerialName("currency") val currency: String? = null,
    @SerialName("amounts") val amounts: List<OrdersAmountItem>? = null,
)
