package ru.krindra.vknorthtypes.types.orders

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class OrdersAmountItem (
    @SerialName("description") val description: String? = null,
    @SerialName("votes") val votes: String? = null,
    @SerialName("amount") val amount: Double? = null,
)
