package ru.krindra.vknorthtypes.types.orders

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias OrdersChangeStateRawResponse = String
@Serializable()
data class OrdersChangeStateResponse (
    val response: OrdersChangeStateRawResponse
)

