package ru.krindra.vknorthtypes.types.orders

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class OrdersOrder (
    @SerialName("item") val item: String,
    @SerialName("status") val status: String,
    @SerialName("transaction_id") val transactionId: String? = null,
    @SerialName("amount") val amount: String,
    @SerialName("user_id") val userId: String,
    @SerialName("app_order_id") val appOrderId: String,
    @SerialName("date") val date: String,
    @SerialName("cancel_transaction_id") val cancelTransactionId: String? = null,
    @SerialName("id") val id: String,
    @SerialName("receiver_id") val receiverId: String,
)
