package ru.krindra.vknorthtypes.types.newsfeed

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class NewsfeedItemFriend (
    @SerialName("short_text_rate") val shortTextRate: Double? = null,
    @SerialName("date") val date: Int/* WARN! Int? = null */,
    @SerialName("friends") val friends: NewsfeedItemFriendFriends? = null,
    @SerialName("type") val type: NewsfeedNewsfeedItemType/* WARN! WallPostType? = null */,
    @SerialName("source_id") val sourceId: Long,
    @SerialName("feedback") val feedback: NewsfeedItemWallpostFeedback? = null,
)
