package ru.krindra.vknorthtypes.types.newsfeed

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class NewsfeedCommentsItemBase (
    @SerialName("source_id") val sourceId: Long? = null,
    @SerialName("type") val type: NewsfeedNewsfeedItemType/* WARN! WallPostType? = null */,
    @SerialName("date") val date: Int? = null,
    @SerialName("post_id") val postId: Long? = null,
)
