package ru.krindra.vknorthtypes.types.newsfeed

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.photos.PhotosPhoto

/**
 *
 * @param count Tags number
 * @param items 
 */
@Serializable
data class NewsfeedItemPhotoTagPhotoTags (
    @SerialName("items") val items: List<PhotosPhoto>? = null,
    @SerialName("count") val count: Int? = null,
)
