package ru.krindra.vknorthtypes.types.newsfeed

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param type 
 * @param question 
 * @param answers 
 * @param starsCount 
 * @param descriptions 
 * @param gratitude 
 * @param trackCode 
 */
@Serializable
data class NewsfeedItemWallpostFeedback (
    @SerialName("descriptions") val descriptions: List<String>? = null,
    @SerialName("gratitude") val gratitude: String? = null,
    @SerialName("stars_count") val starsCount: Int? = null,
    @SerialName("answers") val answers: List<NewsfeedItemWallpostFeedbackAnswer>? = null,
    @SerialName("type") val type: NewsfeedItemWallpostFeedbackType,
    @SerialName("track_code") val trackCode: String? = null,
    @SerialName("question") val question: String,
)
