package ru.krindra.vknorthtypes.types.newsfeed

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class NewsfeedGetListsResponse (
    val response: NewsfeedGetListsRawResponse
) {
    @Serializable
    data class NewsfeedGetListsRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<NewsfeedList>,
    )
}

