package ru.krindra.vknorthtypes.types.newsfeed

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class NewsfeedItemDigestFooter (
    @SerialName("style") val style: String,
    @SerialName("button") val button: NewsfeedItemDigestButton? = null,
    @SerialName("text") val text: String,
)
