package ru.krindra.vknorthtypes.types.newsfeed

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.groups.GroupsGroupFull

import ru.krindra.vknorthtypes.types.users.UsersUserFull


@Serializable
data class NewsfeedGetCommentsResponse (
    val response: NewsfeedGetCommentsRawResponse
) {
    /**
     *
     * @param items 
     * @param profiles 
     * @param groups 
     * @param nextFrom Next from value
     */
    @Serializable
    data class NewsfeedGetCommentsRawResponse (
        @SerialName("items") val items: List<NewsfeedCommentsItem>,
        @SerialName("profiles") val profiles: List<UsersUserFull>,
        @SerialName("groups") val groups: List<GroupsGroupFull>,
        @SerialName("next_from") val nextFrom: String? = null,
    )
}

