package ru.krindra.vknorthtypes.types.newsfeed

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.photos.PhotosPhotoSizes
import ru.krindra.vknorthtypes.types.photos.PhotosImage
import ru.krindra.vknorthtypes.types.base.BaseObjectCount
import ru.krindra.vknorthtypes.types.base.BasePropertyExists
import ru.krindra.vknorthtypes.types.base.BaseRepostsInfo
import ru.krindra.vknorthtypes.types.base.BaseBoolInt
import ru.krindra.vknorthtypes.types.base.BaseLikes

@Serializable
data class NewsfeedCommentsItemTypePhoto (
    @SerialName("reposts") val reposts: BaseRepostsInfo? = null,
    @SerialName("images") val images: List<PhotosImage>? = null,
    @SerialName("comments") val comments: NewsfeedCommentsBase? = null/* WARN! BaseObjectCount? = null */,
    @SerialName("real_offset") val realOffset: Int? = null,
    @SerialName("can_comment") val canComment: BaseBoolInt? = null,
    @SerialName("source_id") val sourceId: Long? = null,
    @SerialName("width") val width: Int? = null,
    @SerialName("access_key") val accessKey: String? = null,
    @SerialName("photo_256") val photo256: String? = null,
    @SerialName("text") val text: String? = null,
    @SerialName("post_id") val postId: Long? = null,
    @SerialName("tags") val tags: BaseObjectCount? = null,
    @SerialName("owner_id") val ownerId: Long,
    @SerialName("type") val type: NewsfeedNewsfeedItemType/* WARN! WallPostType? = null */,
    @SerialName("likes") val likes: BaseLikes? = null,
    @SerialName("long") val long: Double? = null,
    @SerialName("vertical_align") val verticalAlign: String? = null,
    @SerialName("hidden") val hidden: BasePropertyExists? = null,
    @SerialName("square_crop") val squareCrop: String? = null,
    @SerialName("album_id") val albumId: Long,
    @SerialName("id") val id: Long,
    @SerialName("date") val date: Int/* WARN! Int? = null */,
    @SerialName("sizes") val sizes: List<PhotosPhotoSizes>? = null,
    @SerialName("lat") val lat: Double? = null,
    @SerialName("place") val place: String? = null,
    @SerialName("has_tags") val hasTags: Boolean,
    @SerialName("height") val height: Int? = null,
    @SerialName("user_id") val userId: Long? = null,
)
