package ru.krindra.vknorthtypes.types.newsfeed

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.audio.AudioAudio

@Serializable
data class NewsfeedItemAudioAudio (
    @SerialName("items") val items: List<AudioAudio>? = null,
    @SerialName("count") val count: Int? = null,
)
