package ru.krindra.vknorthtypes.types.newsfeed

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class NewsfeedItemDigestHeader (
    @SerialName("subtitle") val subtitle: String? = null,
    @SerialName("title") val title: String,
    @SerialName("button") val button: NewsfeedItemDigestButton? = null,
    @SerialName("badge_text") val badgeText: String? = null,
    @SerialName("style") val style: String,
)
