package ru.krindra.vknorthtypes.types.polls

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class PollsVotersUsers (
    @SerialName("items") val items: List<Int>? = null,
    @SerialName("count") val count: Int? = null,
)
