package ru.krindra.vknorthtypes.types.polls

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class PollsAnswer (
    @SerialName("id") val id: Long,
    @SerialName("rate") val rate: Double,
    @SerialName("votes") val votes: Int,
    @SerialName("text") val text: String,
)
