package ru.krindra.vknorthtypes.types.comment

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.wall.WallWallComment

@Serializable
data class CommentThread (
    @SerialName("can_post") val canPost: Boolean? = null,
    @SerialName("show_reply_button") val showReplyButton: Boolean? = null,
    @SerialName("groups_can_post") val groupsCanPost: Boolean? = null,
    @SerialName("count") val count: Int,
    @SerialName("items") val items: List<WallWallComment>? = null,
)
