package ru.krindra.vknorthtypes.types.users

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class UsersGetFollowersFieldsResponse (
    val response: UsersGetFollowersFieldsRawResponse
) {
    @Serializable
    data class UsersGetFollowersFieldsRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("friends_count") val friendsCount: Int? = null,
        @SerialName("items") val items: List<UsersUserFull>,
    )
}

