package ru.krindra.vknorthtypes.types.users

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param skype User's Skype nickname
 * @param facebook User's Facebook account
 * @param facebookName User's Facebook name
 * @param twitter User's Twitter account
 * @param livejournal User's Livejournal account
 * @param instagram User's Instagram account
 */
@Serializable
data class UsersUserConnections (
    @SerialName("facebook") val facebook: String,
    @SerialName("facebook_name") val facebookName: String? = null,
    @SerialName("skype") val skype: String,
    @SerialName("livejournal") val livejournal: String? = null,
    @SerialName("instagram") val instagram: String,
    @SerialName("twitter") val twitter: String,
)
