package ru.krindra.vknorthtypes.types.users

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.groups.GroupsGroupsArray


@Serializable
data class UsersGetSubscriptionsResponse (
    val response: UsersGetSubscriptionsRawResponse
) {
    @Serializable
    data class UsersGetSubscriptionsRawResponse (
        @SerialName("users") val users: UsersUsersArray,
        @SerialName("groups") val groups: GroupsGroupsArray,
    )
}

