package ru.krindra.vknorthtypes.types.users

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param id ID of school, university, company group
 * @param name Name of occupation
 * @param type Type of occupation
 * @param graduateYear 
 * @param countryId 
 * @param cityId 
 */
@Serializable
data class UsersOccupation (
    @SerialName("graduate_year") val graduateYear: Int? = null,
    @SerialName("id") val id: Long? = null,
    @SerialName("type") val type: String? = null,
    @SerialName("city_id") val cityId: Long? = null,
    @SerialName("name") val name: String? = null,
    @SerialName("country_id") val countryId: Long? = null,
)
