package ru.krindra.vknorthtypes.types.users

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.database.DatabaseLanguageFull

@Serializable
data class UsersPersonal (
    @SerialName("inspired_by") val inspiredBy: String? = null,
    @SerialName("religion") val religion: String? = null,
    @SerialName("alcohol") val alcohol: Int? = null,
    @SerialName("langs") val langs: List<String>? = null,
    @SerialName("life_main") val lifeMain: Int? = null,
    @SerialName("people_main") val peopleMain: Int? = null,
    @SerialName("religion_id") val religionId: Long? = null,
    @SerialName("smoking") val smoking: Int? = null,
    @SerialName("langs_full") val langsFull: List<DatabaseLanguageFull>? = null,
    @SerialName("political") val political: Int? = null,
)
