package ru.krindra.vknorthtypes.types.users

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class UsersExports (
    @SerialName("livejournal") val livejournal: Int? = null,
    @SerialName("twitter") val twitter: Int? = null,
    @SerialName("facebook") val facebook: Int? = null,
)
