package ru.krindra.vknorthtypes.types.account

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AccountGetActiveOffersResponse (
    val response: AccountGetActiveOffersRawResponse
) {
    @Serializable
    data class AccountGetActiveOffersRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<AccountOffer>,
    )
}

