package ru.krindra.vknorthtypes.types.account

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AccountGetProfileInfoRawResponse = AccountUserSettings
@Serializable
data class AccountGetProfileInfoResponse (
    val response: AccountGetProfileInfoRawResponse
)

