package ru.krindra.vknorthtypes.types.account

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseBoolInt

@Serializable
data class AccountInfo (
    @SerialName("https_required") val httpsRequired: BaseBoolInt? = null,
    @SerialName("_2fa_required") val _2faRequired: BaseBoolInt? = null,
    @SerialName("country") val country: String? = null,
    @SerialName("own_posts_default") val ownPostsDefault: BaseBoolInt? = null,
    @SerialName("lang") val lang: Int? = null,
    @SerialName("intro") val intro: BaseBoolInt? = null,
    @SerialName("no_wall_replies") val noWallReplies: BaseBoolInt? = null,
)
