package ru.krindra.vknorthtypes.types.account

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AccountNameRequest (
    @SerialName("first_name") val firstName: String? = null,
    @SerialName("id") val id: Long? = null,
    @SerialName("status") val status: AccountNameRequestStatus? = null,
    @SerialName("link_href") val linkHref: String? = null,
    @SerialName("last_name") val lastName: String? = null,
    @SerialName("lang") val lang: String? = null,
    @SerialName("link_label") val linkLabel: String? = null,
)
