package ru.krindra.vknorthtypes.types.account

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param count Items count
 * @param items 
 */
@Serializable
data class AccountPushConversations (
    @SerialName("count") val count: Int? = null,
    @SerialName("items") val items: List<AccountPushConversationsItem>? = null,
)
