package ru.krindra.vknorthtypes.types.account

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AccountGetInfoRawResponse = AccountInfo
@Serializable
data class AccountGetInfoResponse (
    val response: AccountGetInfoRawResponse
)

