package ru.krindra.vknorthtypes.types.pages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias PagesGetVersionRawResponse = PagesWikipageFull
@Serializable
data class PagesGetVersionResponse (
    val response: PagesGetVersionRawResponse
)

