package ru.krindra.vknorthtypes.types.pages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias PagesGetTitlesRawResponse = List<PagesWikipage>
@Serializable
data class PagesGetTitlesResponse (
    val response: PagesGetTitlesRawResponse
)

