package ru.krindra.vknorthtypes.types.pages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias PagesSaveRawResponse = Int
@Serializable()
data class PagesSaveResponse (
    val response: PagesSaveRawResponse
)

