package ru.krindra.vknorthtypes.types.notes

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseBoolInt

@Serializable
data class NotesNote (
    @SerialName("id") val id: Long,
    @SerialName("privacy_view") val privacyView: List<String>? = null,
    @SerialName("owner_id") val ownerId: Long,
    @SerialName("date") val date: Int,
    @SerialName("title") val title: String,
    @SerialName("can_comment") val canComment: BaseBoolInt? = null,
    @SerialName("view_url") val viewUrl: String,
    @SerialName("read_comments") val readComments: Int? = null,
    @SerialName("text_wiki") val textWiki: String? = null,
    @SerialName("text") val text: String? = null,
    @SerialName("comments") val comments: Int,
    @SerialName("privacy_comment") val privacyComment: List<String>? = null,
)
