package ru.krindra.vknorthtypes.types.notes

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias NotesGetByIdRawResponse = NotesNote
@Serializable
data class NotesGetByIdResponse (
    val response: NotesGetByIdRawResponse
)

