package ru.krindra.vknorthtypes.types.status

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.audio.AudioAudio

/**
 *
 * @param text Status text
 * @param audio 
 */
@Serializable
data class StatusStatus (
    @SerialName("audio") val audio: AudioAudio? = null,
    @SerialName("text") val text: String,
)
