package ru.krindra.vknorthtypes.types.notifications

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias NotificationsSendMessageRawResponse = List<NotificationsSendMessageItem>
@Serializable
data class NotificationsSendMessageResponse (
    val response: NotificationsSendMessageRawResponse
)

