package ru.krindra.vknorthtypes.types.notifications

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class NotificationsReply (
    @SerialName("id") val id: Long? = null,
    @SerialName("text") val text: Int? = null,
    @SerialName("date") val date: Int? = null,
)
