package ru.krindra.vknorthtypes.types.stats

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class StatsViews (
    @SerialName("visitors") val visitors: Int? = null,
    @SerialName("mobile_views") val mobileViews: Int? = null,
    @SerialName("cities") val cities: List<StatsCity>? = null,
    @SerialName("age") val age: List<StatsSexAge>? = null,
    @SerialName("views") val views: Int? = null,
    @SerialName("sex_age") val sexAge: List<StatsSexAge>? = null,
    @SerialName("countries") val countries: List<StatsCountry>? = null,
    @SerialName("sex") val sex: List<StatsSexAge>? = null,
)
