package ru.krindra.vknorthtypes.types.stats

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class StatsWallpostStat (
    @SerialName("reach_subscribers_count") val reachSubscribersCount: Int? = null,
    @SerialName("hide") val hide: Int? = null,
    @SerialName("join_group") val joinGroup: Int? = null,
    @SerialName("reach_total") val reachTotal: Int? = null,
    @SerialName("reach_total_count") val reachTotalCount: Int? = null,
    @SerialName("reach_ads") val reachAds: Int? = null,
    @SerialName("report") val report: Int? = null,
    @SerialName("reach_subscribers") val reachSubscribers: Int? = null,
    @SerialName("sex_age") val sexAge: List<StatsSexAge>? = null,
    @SerialName("reach_viral") val reachViral: Int? = null,
    @SerialName("unsubscribe") val unsubscribe: Int? = null,
    @SerialName("post_id") val postId: Long? = null,
    @SerialName("to_group") val toGroup: Int? = null,
    @SerialName("links") val links: Int? = null,
)
