package ru.krindra.vknorthtypes.types.stats

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias StatsGetRawResponse = List<StatsPeriod>
@Serializable
data class StatsGetResponse (
    val response: StatsGetRawResponse
)

