package ru.krindra.vknorthtypes.types.stats

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class StatsCountry (
    @SerialName("name") val name: String? = null,
    @SerialName("value") val value: Int? = null,
    @SerialName("code") val code: String? = null,
    @SerialName("count") val count: Int? = null,
)
