package ru.krindra.vknorthtypes.types.wall

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseLink

@Serializable
data class WallPostSource (
    @SerialName("link") val link: BaseLink? = null,
    @SerialName("url") val url: String? = null,
    @SerialName("platform") val platform: String? = null,
    @SerialName("data") val data: String? = null,
    @SerialName("type") val type: WallPostSourceType? = null,
)
