package ru.krindra.vknorthtypes.types.wall

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class WallGetCommentsResponse (
    val response: WallGetCommentsRawResponse
) {
    /**
     *
     * @param count Total number
     * @param items 
     * @param currentLevelCount Count of replies of current level
     * @param canPost Information whether current user can comment the post
     * @param showReplyButton 
     * @param groupsCanPost Information whether groups can comment the post
     */
    @Serializable
    data class WallGetCommentsRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<WallWallComment>,
        @SerialName("current_level_count") val currentLevelCount: Int? = null,
        @SerialName("can_post") val canPost: Boolean? = null,
        @SerialName("show_reply_button") val showReplyButton: Boolean? = null,
        @SerialName("groups_can_post") val groupsCanPost: Boolean? = null,
    )
}

