package ru.krindra.vknorthtypes.types.wall

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class WallGeo (
    @SerialName("type") val type: String? = null,
    @SerialName("showmap") val showmap: Int? = null,
    @SerialName("coordinates") val coordinates: String? = null,
)
