package ru.krindra.vknorthtypes.types.wall

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class WallGraffiti (
    @SerialName("photo_200") val photo200: String? = null,
    @SerialName("id") val id: Long? = null,
    @SerialName("url") val url: String? = null,
    @SerialName("owner_id") val ownerId: Long? = null,
    @SerialName("width") val width: Int? = null,
    @SerialName("height") val height: Int? = null,
    @SerialName("access_key") val accessKey: String? = null,
    @SerialName("photo_586") val photo586: String? = null,
)
