package ru.krindra.vknorthtypes.types.wall

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class WallPostAdsStealthResponse (
    val response: WallPostAdsStealthRawResponse
) {
    /**
     *
     * @param postId Created post ID
     */
    @Serializable
    data class WallPostAdsStealthRawResponse (
        @SerialName("post_id") val postId: Long,
    )
}

