package ru.krindra.vknorthtypes.types.wall

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class WallGetCommentResponse (
    val response: WallGetCommentRawResponse
) {
    @Serializable
    data class WallGetCommentRawResponse (
        @SerialName("items") val items: List<WallWallComment>,
        @SerialName("can_post") val canPost: Boolean? = null,
        @SerialName("show_reply_button") val showReplyButton: Boolean? = null,
        @SerialName("groups_can_post") val groupsCanPost: Boolean? = null,
    )
}

