package ru.krindra.vknorthtypes.types.wall

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class WallWallpostDonut (
    @SerialName("is_donut") val isDonut: Boolean,
    @SerialName("placeholder") val placeholder: WallWallpostDonutPlaceholder? = null,
    @SerialName("paid_duration") val paidDuration: Int? = null,
    @SerialName("can_publish_free_copy") val canPublishFreeCopy: Boolean? = null,
    @SerialName("edit_mode") val editMode: String? = null,
)
