package ru.krindra.vknorthtypes.types.wall

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.newsfeed.NewsfeedItemWallpostFeedback
import ru.krindra.vknorthtypes.types.base.BaseCommentsInfo
import ru.krindra.vknorthtypes.types.base.BaseRepostsInfo
import ru.krindra.vknorthtypes.types.base.BaseLikesInfo
import ru.krindra.vknorthtypes.types.base.BaseBoolInt

@Serializable
data class WallWallpostFull (
    @SerialName("reposts") val reposts: BaseRepostsInfo? = null,
    @SerialName("is_deleted") val isDeleted: Boolean? = null,
    @SerialName("date") val date: Int? = null,
    @SerialName("comments") val comments: BaseCommentsInfo? = null,
    @SerialName("created_by") val createdBy: Int? = null,
    @SerialName("donut") val donut: WallWallpostDonut? = null,
    @SerialName("access_key") val accessKey: String? = null,
    @SerialName("deleted_reason") val deletedReason: String? = null,
    @SerialName("from_id") val fromId: Long? = null,
    @SerialName("copyright") val copyright: WallPostCopyright? = null,
    @SerialName("id") val id: Long? = null,
    @SerialName("feedback") val feedback: NewsfeedItemWallpostFeedback? = null,
    @SerialName("can_edit") val canEdit: BaseBoolInt? = null,
    @SerialName("copy_history") val copyHistory: List<WallWallpostFull>? = null,
    @SerialName("text") val text: String? = null,
    @SerialName("post_id") val postId: Long? = null,
    @SerialName("geo") val geo: WallGeo? = null,
    @SerialName("is_archived") val isArchived: Boolean? = null,
    @SerialName("type") val type: WallPostType? = null,
    @SerialName("parents_stack") val parentsStack: List<Int>? = null,
    @SerialName("post_type") val postType: WallPostType? = null,
    @SerialName("is_pinned") val isPinned: BaseBoolInt? = null,
    @SerialName("likes") val likes: BaseLikesInfo? = null,
    @SerialName("topic_id") val topicId: Long? = null,
    @SerialName("deleted_details") val deletedDetails: String? = null,
    @SerialName("to_id") val toId: Long? = null,
    @SerialName("views") val views: WallViews? = null,
    @SerialName("carousel_offset") val carouselOffset: Int? = null,
    @SerialName("can_pin") val canPin: BaseBoolInt? = null,
    @SerialName("marked_as_ads") val markedAsAds: BaseBoolInt? = null,
    @SerialName("edited") val edited: Int? = null,
    @SerialName("hash") val hash: String? = null,
    @SerialName("short_text_rate") val shortTextRate: Double? = null,
    @SerialName("is_favorite") val isFavorite: Boolean? = null,
    @SerialName("owner_id") val ownerId: Long? = null,
    @SerialName("signer_id") val signerId: Long? = null,
    @SerialName("can_delete") val canDelete: BaseBoolInt? = null,
    @SerialName("post_source") val postSource: WallPostSource? = null,
    @SerialName("attachments") val attachments: List<WallWallpostAttachment>? = null,
)
