package ru.krindra.vknorthtypes.types.search

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class SearchGetHintsResponse (
    val response: SearchGetHintsRawResponse
) {
    /**
     *
     * @param count 
     * @param items 
     * @param suggestedQueries 
     */
    @Serializable
    data class SearchGetHintsRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<SearchHint>,
        @SerialName("suggested_queries") val suggestedQueries: List<String>? = null,
    )
}

