package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param height Image height
 * @param width Image width
 */
@Serializable
data class GroupsPhotoSize (
    @SerialName("height") val height: Int,
    @SerialName("width") val width: Int,
)
