package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias GroupsGetCallbackSettingsRawResponse = GroupsCallbackSettings
@Serializable
data class GroupsGetCallbackSettingsResponse (
    val response: GroupsGetCallbackSettingsRawResponse
)

