package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GroupsGroupCategoryFull (
    @SerialName("page_previews") val pagePreviews: List<GroupsGroup>,
    @SerialName("id") val id: Long,
    @SerialName("name") val name: String,
    @SerialName("page_count") val pageCount: Int,
    @SerialName("subcategories") val subcategories: List<GroupsGroupCategory>? = null,
)
