package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GroupsProfileItem (
    @SerialName("id") val id: Long,
    @SerialName("first_name") val firstName: String,
    @SerialName("photo_50") val photo50: String,
    @SerialName("photo_100") val photo100: String,
)
