package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GroupsGetOnlineStatusResponse (
    val response: GroupsGetOnlineStatusRawResponse
) {
    @Serializable
    data class GroupsGetOnlineStatusRawResponse (
        @SerialName("minutes") val minutes: Int? = null,
        @SerialName("status") val status: GroupsOnlineStatusType,
    )
}

