package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GroupsGetRequestsResponse (
    val response: GroupsGetRequestsRawResponse
) {
    @Serializable
    data class GroupsGetRequestsRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<Int>,
    )
}

