package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias GroupsIsMemberUserIdsRawResponse = List<GroupsMemberStatus>
@Serializable
data class GroupsIsMemberUserIdsResponse (
    val response: GroupsIsMemberUserIdsRawResponse
)

