package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias GroupsGetLongPollServerRawResponse = GroupsLongPollServer
@Serializable
data class GroupsGetLongPollServerResponse (
    val response: GroupsGetLongPollServerRawResponse
)

