package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GroupsCountersGroup (
    @SerialName("market_services") val marketServices: Int? = null,
    @SerialName("audio_playlists") val audioPlaylists: Int? = null,
    @SerialName("clips_followers") val clipsFollowers: Int? = null,
    @SerialName("clips_views") val clipsViews: Int? = null,
    @SerialName("video_playlists") val videoPlaylists: Int? = null,
    @SerialName("addresses") val addresses: Int? = null,
    @SerialName("docs") val docs: Int? = null,
    @SerialName("photos") val photos: Int? = null,
    @SerialName("narratives") val narratives: Int? = null,
    @SerialName("topics") val topics: Int? = null,
    @SerialName("videos_followers") val videosFollowers: Int? = null,
    @SerialName("market") val market: Int? = null,
    @SerialName("articles") val articles: Int? = null,
    @SerialName("clips") val clips: Int? = null,
    @SerialName("audios") val audios: Int? = null,
    @SerialName("videos") val videos: Int? = null,
    @SerialName("podcasts") val podcasts: Int? = null,
    @SerialName("albums") val albums: Int? = null,
    @SerialName("clips_likes") val clipsLikes: Int? = null,
)
