package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GroupsSearchResponse (
    val response: GroupsSearchRawResponse
) {
    @Serializable
    data class GroupsSearchRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<GroupsGroupFull>,
    )
}

