package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseBoolInt

@Serializable
data class GroupsLinksItem (
    @SerialName("edit_title") val editTitle: BaseBoolInt? = null,
    @SerialName("photo_50") val photo50: String? = null,
    @SerialName("name") val name: String? = null,
    @SerialName("id") val id: Long? = null,
    @SerialName("url") val url: String? = null,
    @SerialName("photo_100") val photo100: String? = null,
    @SerialName("image_processing") val imageProcessing: BaseBoolInt? = null,
    @SerialName("desc") val desc: String? = null,
)
