package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GroupsGetCallbackConfirmationCodeResponse (
    val response: GroupsGetCallbackConfirmationCodeRawResponse
) {
    @Serializable
    data class GroupsGetCallbackConfirmationCodeRawResponse (
        @SerialName("code") val code: String,
    )
}

