package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GroupsLongPollServer (
    @SerialName("ts") val ts: String,
    @SerialName("server") val server: String,
    @SerialName("key") val key: String,
)
