package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseCountry
import ru.krindra.vknorthtypes.types.database.DatabaseStation
import ru.krindra.vknorthtypes.types.database.DatabaseCityById

@Serializable
data class GroupsAddress (
    @SerialName("id") val id: Long,
    @SerialName("city_id") val cityId: Long? = null,
    @SerialName("country_id") val countryId: Long? = null,
    @SerialName("city") val city: DatabaseCityById? = null,
    @SerialName("address") val address: String? = null,
    @SerialName("metro_station") val metroStation: DatabaseStation? = null,
    @SerialName("distance") val distance: Int? = null,
    @SerialName("latitude") val latitude: Double? = null,
    @SerialName("country") val country: BaseCountry? = null,
    @SerialName("longitude") val longitude: Double? = null,
    @SerialName("metro_station_id") val metroStationId: Long? = null,
    @SerialName("title") val title: String? = null,
    @SerialName("timetable") val timetable: GroupsAddressTimetable? = null,
    @SerialName("time_offset") val timeOffset: Int? = null,
    @SerialName("work_info_status") val workInfoStatus: GroupsAddressWorkInfoStatus? = null,
    @SerialName("phone") val phone: String? = null,
    @SerialName("additional_address") val additionalAddress: String? = null,
    @SerialName("place_id") val placeId: Long? = null,
)
