package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.users.UsersUserMin


@Serializable
data class GroupsGetInvitesExtendedResponse (
    val response: GroupsGetInvitesExtendedRawResponse
) {
    /**
     *
     * @param count Total communities number
     * @param items 
     * @param profiles 
     * @param groups 
     */
    @Serializable
    data class GroupsGetInvitesExtendedRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<GroupsGroupFull>,
        @SerialName("profiles") val profiles: List<UsersUserMin>,
        @SerialName("groups") val groups: List<GroupsGroupFull>,
    )
}

