package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GroupsMarketProperties (
    @SerialName("using_vkpay_market_app") val usingVkpayMarketApp: Boolean? = null,
    @SerialName("market") val market: GroupsMarketInfo? = null,
    @SerialName("has_market_app") val hasMarketApp: Boolean? = null,
)
