package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GroupsOnlineStatus (
    @SerialName("status") val status: GroupsOnlineStatusType,
    @SerialName("minutes") val minutes: Int? = null,
)
