package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param id User ID
 * @param isCallOperator Allow the manager to accept community calls.
 * @param permissions 
 * @param role 
 */
@Serializable
data class GroupsMemberRole (
    @SerialName("permissions") val permissions: List<GroupsMemberRolePermission>? = null,
    @SerialName("is_call_operator") val isCallOperator: Boolean? = null,
    @SerialName("role") val role: GroupsMemberRoleStatus? = null,
    @SerialName("id") val id: Long,
)
