package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param id 
 * @param name 
 * @param color 
 * @param uses 
 */
@Serializable
data class GroupsGroupTag (
    @SerialName("name") val name: String,
    @SerialName("color") val color: String,
    @SerialName("uses") val uses: Int? = null,
    @SerialName("id") val id: Long,
)
