package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GroupsMemberRole (
    @SerialName("permissions") val permissions: List<GroupsMemberRolePermission>? = null,
    @SerialName("id") val id: Long,
    @SerialName("is_call_operator") val isCallOperator: Boolean? = null,
    @SerialName("role") val role: GroupsMemberRoleStatus? = null,
)
