package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param apiVersion API version used for the events
 * @param events 
 */
@Serializable
data class GroupsCallbackSettings (
    @SerialName("events") val events: GroupsLongPollEvents? = null,
    @SerialName("api_version") val apiVersion: String? = null,
)
