package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GroupsGetMembersFilterResponse (
    val response: GroupsGetMembersFilterRawResponse
) {
    @Serializable
    data class GroupsGetMembersFilterRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<GroupsMemberRole>,
        @SerialName("next_from") val nextFrom: String? = null,
    )
}

