package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class GroupsBanInfo (
    @SerialName("admin_id") val adminId: Long? = null,
    @SerialName("reason") val reason: GroupsBanInfoReason? = null,
    @SerialName("end_date") val endDate: Int? = null,
    @SerialName("date") val date: Int? = null,
    @SerialName("comment_visible") val commentVisible: Boolean? = null,
    @SerialName("comment") val comment: String? = null,
    @SerialName("is_closed") val isClosed: Boolean? = null,
)
