package ru.krindra.vknorthtypes.types.groups

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseObjectWithName

@Serializable
data class GroupsGroupSubcategory (
    @SerialName("id") val id: Long,
    @SerialName("name") val name: String,
    @SerialName("genders") val genders: List<BaseObjectWithName>? = null,
)
