package ru.krindra.vknorthtypes.types.leadForms

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param key 
 * @param value 
 */
@Serializable
data class LeadFormsAnswerItem (
    @SerialName("key") val key: String? = null,
    @SerialName("value") val value: String,
)
