package ru.krindra.vknorthtypes.types.leadForms

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class LeadFormsDeleteResponse (
    val response: LeadFormsDeleteRawResponse
) {
    /**
     *
     * @param formId 
     */
    @Serializable
    data class LeadFormsDeleteRawResponse (
        @SerialName("form_id") val formId: Long,
    )
}

