package ru.krindra.vknorthtypes.types.leadForms

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias LeadFormsUploadUrlRawResponse = String
@Serializable
data class LeadFormsUploadUrlResponse (
    val response: LeadFormsUploadUrlRawResponse
)

