package ru.krindra.vknorthtypes.types.leadForms

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class LeadFormsAnswer (
    @SerialName("answer") val answer: LeadFormsAnswerOneOf,
    @SerialName("key") val key: String,
)
