package ru.krindra.vknorthtypes.types.leadForms

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseBoolInt

/**
 *
 * @param formId 
 * @param groupId 
 * @param photo 
 * @param name 
 * @param title 
 * @param description 
 * @param confirmation 
 * @param siteLinkUrl 
 * @param policyLinkUrl 
 * @param questions 
 * @param active 
 * @param leadsCount 
 * @param pixelCode 
 * @param oncePerUser 
 * @param notifyAdmins 
 * @param notifyEmails 
 * @param url 
 */
@Serializable
data class LeadFormsForm (
    @SerialName("leads_count") val leadsCount: Int,
    @SerialName("notify_admins") val notifyAdmins: String? = null,
    @SerialName("description") val description: String? = null,
    @SerialName("form_id") val formId: Long,
    @SerialName("once_per_user") val oncePerUser: Int? = null,
    @SerialName("photo") val photo: String? = null,
    @SerialName("active") val active: BaseBoolInt? = null,
    @SerialName("notify_emails") val notifyEmails: String? = null,
    @SerialName("policy_link_url") val policyLinkUrl: String? = null,
    @SerialName("title") val title: String? = null,
    @SerialName("site_link_url") val siteLinkUrl: String? = null,
    @SerialName("name") val name: String? = null,
    @SerialName("url") val url: String,
    @SerialName("questions") val questions: List<LeadFormsQuestionItem>? = null,
    @SerialName("pixel_code") val pixelCode: String? = null,
    @SerialName("group_id") val groupId: Long,
    @SerialName("confirmation") val confirmation: String? = null,
)
