package ru.krindra.vknorthtypes.types.database

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias DatabaseGetCitiesByIdRawResponse = List<DatabaseCityById>
@Serializable
data class DatabaseGetCitiesByIdResponse (
    val response: DatabaseGetCitiesByIdRawResponse
)

