package ru.krindra.vknorthtypes.types.database

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class DatabaseGetUniversitiesResponse (
    val response: DatabaseGetUniversitiesRawResponse
) {
    /**
     *
     * @param count Total number
     * @param items 
     */
    @Serializable
    data class DatabaseGetUniversitiesRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<DatabaseUniversity>,
    )
}

