package ru.krindra.vknorthtypes.types.database

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseBoolInt

@Serializable
data class DatabaseCity (
    @SerialName("id") val id: Long,
    @SerialName("important") val important: BaseBoolInt? = null,
    @SerialName("title") val title: String,
    @SerialName("area") val area: String? = null,
    @SerialName("region") val region: String? = null,
    @SerialName("country") val country: String? = null,
)
