package ru.krindra.vknorthtypes.types.database

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class DatabaseLanguageFull (
    @SerialName("id") val id: Long,
    @SerialName("native_name") val nativeName: String,
)
