package ru.krindra.vknorthtypes.types.database

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import ru.krindra.vknorthtypes.types.base.BaseObject

typealias DatabaseSchoolClass = BaseObject

