package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias MessagesGetConversationsByIdExtendedRawResponse = MessagesGetConversationByIdExtended
@Serializable
data class MessagesGetConversationsByIdExtendedResponse (
    val response: MessagesGetConversationsByIdExtendedRawResponse
)

