package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias MessagesMarkAsImportantDeprecatedRawResponse = List<Int>
@Serializable
data class MessagesMarkAsImportantDeprecatedResponse (
    val response: MessagesMarkAsImportantDeprecatedRawResponse
)

