package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias MessagesGetChatChatIdsRawResponse = List<MessagesChat>
@Serializable
data class MessagesGetChatChatIdsResponse (
    val response: MessagesGetChatChatIdsRawResponse
)

