package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MessagesGetReactionsAssetsResponse (
    val response: MessagesGetReactionsAssetsRawResponse
) {
    @Serializable
    data class MessagesGetReactionsAssetsRawResponse (
        @SerialName("version") val version: Int,
        @SerialName("assets") val assets: List<MessagesReactionAssetItem>,
        @SerialName("override_assets") val overrideAssets: List<MessagesReactionAssetItem>? = null,
    )
}

