package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MessagesDeleteChatPhotoResponse (
    val response: MessagesDeleteChatPhotoRawResponse
) {
    /**
     *
     * @param messageId Service message ID
     * @param chat 
     */
    @Serializable
    data class MessagesDeleteChatPhotoRawResponse (
        @SerialName("message_id") val messageId: Long? = null,
        @SerialName("chat") val chat: MessagesChat? = null,
    )
}

