package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias MessagesGetLastActivityRawResponse = MessagesLastActivity
@Serializable
data class MessagesGetLastActivityResponse (
    val response: MessagesGetLastActivityRawResponse
)

