package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MessagesPushSettings (
    @SerialName("disabled_mass_mentions") val disabledMassMentions: Boolean? = null,
    @SerialName("no_sound") val noSound: Boolean,
    @SerialName("disabled_mentions") val disabledMentions: Boolean? = null,
    @SerialName("disabled_until") val disabledUntil: Int? = null,
    @SerialName("disabled_forever") val disabledForever: Boolean,
)
