package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MessagesReactionCountersResponseItem (
    @SerialName("counters") val counters: List<MessagesReactionCounterResponseItem>,
    @SerialName("cmid") val cmid: Long,
)
