package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias MessagesGetConversationMembersRawResponse = MessagesGetConversationMembers
@Serializable
data class MessagesGetConversationMembersResponse (
    val response: MessagesGetConversationMembersRawResponse
)

