package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias MessagesSendDeprecatedRawResponse = Int
/**
 *
 * Message ID
 * 
 */
@Serializable
data class MessagesSendDeprecatedResponse (
    val response: MessagesSendDeprecatedRawResponse
)

