package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MessagesLongpollMessages (
    @SerialName("items") val items: List<MessagesMessage>? = null,
    @SerialName("count") val count: Int? = null,
)
