package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias MessagesGetChatRawResponse = MessagesChat
@Serializable
data class MessagesGetChatResponse (
    val response: MessagesGetChatRawResponse
)

