package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MessagesKeyboardButton (
    @SerialName("action") val action: MessagesKeyboardButtonPropertyAction,
    @SerialName("color") val color: String? = null,
)
