package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias MessagesSendUserIdsRawResponse = List<MessagesSendUserIdsResponseItem>
@Serializable
data class MessagesSendUserIdsResponse (
    val response: MessagesSendUserIdsRawResponse
)

