package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias MessagesGetChatChatIdsFieldsRawResponse = List<MessagesChatFull>
@Serializable
data class MessagesGetChatChatIdsFieldsResponse (
    val response: MessagesGetChatChatIdsFieldsRawResponse
)

