package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param status Status of message request
 * @param inviterId Message request sender id
 * @param requestDate Message request date
 */
@Serializable
data class MessagesMessageRequestData (
    @SerialName("inviter_id") val inviterId: Long? = null,
    @SerialName("status") val status: String? = null,
    @SerialName("request_date") val requestDate: Int? = null,
)
