package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MessagesKeyboardButtonActionOpenLink (
    @SerialName("type") val type: String,
    @SerialName("link") val link: String,
    @SerialName("label") val label: String,
    @SerialName("payload") val payload: String? = null,
)
