package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MessagesMessageActionPhoto (
    @SerialName("photo_200") val photo200: String,
    @SerialName("photo_50") val photo50: String,
    @SerialName("photo_100") val photo100: String,
)
