package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseMessageError
import ru.krindra.vknorthtypes.types.base.BaseBoolInt

@Serializable
data class MessagesDeleteFullResponseItem (
    @SerialName("message_id") val messageId: Long? = null,
    @SerialName("response") val response: BaseBoolInt? = null,
    @SerialName("peer_id") val peerId: Long? = null,
    @SerialName("conversation_message_id") val conversationMessageId: Long? = null,
    @SerialName("error") val error: BaseMessageError? = null,
)
