package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MessagesMessageAction (
    @SerialName("email") val email: String? = null,
    @SerialName("message") val message: String? = null,
    @SerialName("type") val type: MessagesMessageActionStatus,
    @SerialName("conversation_message_id") val conversationMessageId: Long? = null,
    @SerialName("member_id") val memberId: Long? = null,
    @SerialName("text") val text: String? = null,
    @SerialName("photo") val photo: MessagesMessageActionPhoto? = null,
)
