package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.groups.GroupsGroupFull

import ru.krindra.vknorthtypes.types.users.UsersUser


@Serializable
data class MessagesGetImportantMessagesResponse (
    val response: MessagesGetImportantMessagesRawResponse
) {
    /**
     *
     * @param messages 
     * @param profiles 
     * @param groups 
     * @param conversations 
     */
    @Serializable
    data class MessagesGetImportantMessagesRawResponse (
        @SerialName("messages") val messages: MessagesMessagesArray,
        @SerialName("profiles") val profiles: List<UsersUser>? = null,
        @SerialName("groups") val groups: List<GroupsGroupFull>? = null,
        @SerialName("conversations") val conversations: List<MessagesConversation>? = null,
    )
}

