package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.groups.GroupsGroupFull
import ru.krindra.vknorthtypes.types.users.UsersUserFull

@Serializable
data class MessagesGetConversationMembers (
    @SerialName("count") val count: Int,
    @SerialName("chat_restrictions") val chatRestrictions: MessagesChatRestrictions? = null,
    @SerialName("profiles") val profiles: List<UsersUserFull>? = null,
    @SerialName("groups") val groups: List<GroupsGroupFull>? = null,
    @SerialName("items") val items: List<MessagesConversationMember>,
)
