package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MessagesLongpollParams (
    @SerialName("ts") val ts: Int,
    @SerialName("server") val server: String,
    @SerialName("key") val key: String,
    @SerialName("pts") val pts: Int? = null,
)
