package ru.krindra.vknorthtypes.types.messages

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MessagesForward (
    @SerialName("conversation_message_ids") val conversationMessageIds: List<Int>? = null,
    @SerialName("is_reply") val isReply: Boolean? = null,
    @SerialName("peer_id") val peerId: Long? = null,
    @SerialName("owner_id") val ownerId: Long? = null,
    @SerialName("message_ids") val messageIds: List<Int>? = null,
)
