package ru.krindra.vknorthtypes.types.photos

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias PhotosGetAlbumsCountRawResponse = Int
/**
 *
 * Albums number
 * 
 */
@Serializable
data class PhotosGetAlbumsCountResponse (
    val response: PhotosGetAlbumsCountRawResponse
)

