package ru.krindra.vknorthtypes.types.photos

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.wall.WallWallComment


@Serializable
data class PhotosGetCommentsResponse (
    val response: PhotosGetCommentsRawResponse
) {
    /**
     *
     * @param count Total number
     * @param realOffset Real offset of the comments
     * @param items 
     */
    @Serializable
    data class PhotosGetCommentsRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("real_offset") val realOffset: Int? = null,
        @SerialName("items") val items: List<WallWallComment>,
    )
}

