package ru.krindra.vknorthtypes.types.photos

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias PhotosCreateCommentRawResponse = Int
@Serializable()
data class PhotosCreateCommentResponse (
    val response: PhotosCreateCommentRawResponse
)

