package ru.krindra.vknorthtypes.types.photos

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.groups.GroupsGroupFull

import ru.krindra.vknorthtypes.types.users.UsersUserFull

import ru.krindra.vknorthtypes.types.wall.WallWallComment


@Serializable
data class PhotosGetCommentsExtendedResponse (
    val response: PhotosGetCommentsExtendedRawResponse
) {
    /**
     *
     * @param count Total number
     * @param realOffset Real offset of the comments
     * @param items 
     * @param profiles 
     * @param groups 
     */
    @Serializable
    data class PhotosGetCommentsExtendedRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("real_offset") val realOffset: Int? = null,
        @SerialName("items") val items: List<WallWallComment>,
        @SerialName("profiles") val profiles: List<UsersUserFull>,
        @SerialName("groups") val groups: List<GroupsGroupFull>,
    )
}

