package ru.krindra.vknorthtypes.types.photos

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseBoolInt

@Serializable
data class PhotosPhotoTag (
    @SerialName("id") val id: Long,
    @SerialName("tagged_name") val taggedName: String,
    @SerialName("user_id") val userId: Long,
    @SerialName("date") val date: Int,
    @SerialName("viewed") val viewed: BaseBoolInt,
    @SerialName("y") val y: Double,
    @SerialName("x") val x: Double,
    @SerialName("x2") val x2: Double,
    @SerialName("y2") val y2: Double,
    @SerialName("placer_id") val placerId: Long,
    @SerialName("description") val description: String? = null,
)
