package ru.krindra.vknorthtypes.types.photos

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseImage


@Serializable
data class PhotosSaveOwnerCoverPhotoResponse (
    val response: PhotosSaveOwnerCoverPhotoRawResponse
) {
    /**
     *
     * @param images 
     */
    @Serializable
    data class PhotosSaveOwnerCoverPhotoRawResponse (
        @SerialName("images") val images: List<BaseImage>? = null,
    )
}

