package ru.krindra.vknorthtypes.types.photos

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias PhotosGetByIdRawResponse = List<PhotosPhoto>
@Serializable
data class PhotosGetByIdResponse (
    val response: PhotosGetByIdRawResponse
)

