package ru.krindra.vknorthtypes.types.photos

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias PhotosSaveMarketPhotoRawResponse = List<PhotosPhoto>
@Serializable
data class PhotosSaveMarketPhotoResponse (
    val response: PhotosSaveMarketPhotoRawResponse
)

