package ru.krindra.vknorthtypes.types.photos

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class PhotosPhotoUpload (
    @SerialName("fallback_upload_url") val fallbackUploadUrl: String? = null,
    @SerialName("user_id") val userId: Long,
    @SerialName("upload_url") val uploadUrl: String,
    @SerialName("group_id") val groupId: Long? = null,
    @SerialName("album_id") val albumId: Long,
)
