package ru.krindra.vknorthtypes.types.photos

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseBoolInt


@Serializable
data class PhotosGetAllResponse (
    val response: PhotosGetAllRawResponse
) {
    /**
     *
     * @param count Total number
     * @param items 
     * @param more Information whether next page is presented
     */
    @Serializable
    data class PhotosGetAllRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<PhotosPhoto>,
        @SerialName("more") val more: BaseBoolInt? = null,
    )
}

