package ru.krindra.vknorthtypes.types.photos

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias PhotosSaveWallPhotoRawResponse = List<PhotosPhoto>
@Serializable
data class PhotosSaveWallPhotoResponse (
    val response: PhotosSaveWallPhotoRawResponse
)

