package ru.krindra.vknorthtypes.types.photos

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class PhotosMarketAlbumUploadResponse (
    val response: PhotosMarketAlbumUploadRawResponse
) {
    /**
     *
     * @param gid Community ID
     * @param hash Uploading hash
     * @param photo Uploaded photo data
     * @param server Upload server number
     */
    @Serializable
    data class PhotosMarketAlbumUploadRawResponse (
        @SerialName("gid") val gid: Long? = null,
        @SerialName("hash") val hash: String? = null,
        @SerialName("photo") val photo: String? = null,
        @SerialName("server") val server: Int? = null,
    )
}

