package ru.krindra.vknorthtypes.types.photos

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param height Height of the photo in px.
 * @param type 
 * @param url Photo URL.
 * @param width Width of the photo in px.
 */
@Serializable
data class PhotosImage (
    @SerialName("width") val width: Int? = null,
    @SerialName("height") val height: Int? = null,
    @SerialName("type") val type: PhotosImageType? = null,
    @SerialName("url") val url: String? = null,
)
