package ru.krindra.vknorthtypes.types.photos

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class PhotosPhotoUploadResponse (
    val response: PhotosPhotoUploadRawResponse
) {
    /**
     *
     * @param aid Album ID
     * @param hash Uploading hash
     * @param photo Uploaded photo data
     * @param photosList Uploaded photos data
     * @param server Upload server number
     */
    @Serializable
    data class PhotosPhotoUploadRawResponse (
        @SerialName("aid") val aid: Long? = null,
        @SerialName("hash") val hash: String? = null,
        @SerialName("photo") val photo: String? = null,
        @SerialName("photos_list") val photosList: String? = null,
        @SerialName("server") val server: Int? = null,
    )
}

