package ru.krindra.vknorthtypes.types.store

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import ru.krindra.vknorthtypes.types.base.BaseStickersList

typealias StoreStickersKeywordStickers = BaseStickersList

