package ru.krindra.vknorthtypes.types.store

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class StoreStickersKeywordSticker (
    @SerialName("pack_id") val packId: Long,
    @SerialName("sticker_id") val stickerId: Long,
)
