package ru.krindra.vknorthtypes.types.friends

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias FriendsAreFriendsExtendedRawResponse = List<FriendsFriendExtendedStatus>
@Serializable
data class FriendsAreFriendsExtendedResponse (
    val response: FriendsAreFriendsExtendedRawResponse
)

