package ru.krindra.vknorthtypes.types.friends

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class FriendsGetOnlineOnlineMobileResponse (
    val response: FriendsGetOnlineOnlineMobileRawResponse
) {
    /**
     *
     * @param online 
     * @param onlineMobile 
     */
    @Serializable
    data class FriendsGetOnlineOnlineMobileRawResponse (
        @SerialName("online") val online: List<Int>,
        @SerialName("online_mobile") val onlineMobile: List<Int>,
    )
}

