package ru.krindra.vknorthtypes.types.friends

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias FriendsGetOnlineRawResponse = List<Int>
@Serializable
data class FriendsGetOnlineResponse (
    val response: FriendsGetOnlineRawResponse
)

