package ru.krindra.vknorthtypes.types.friends

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class FriendsRequestsMutual (
    @SerialName("users") val users: List<Int>? = null,
    @SerialName("count") val count: Int? = null,
)
