package ru.krindra.vknorthtypes.types.friends

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class FriendsGetRequestsExtendedResponse (
    val response: FriendsGetRequestsExtendedRawResponse
) {
    @Serializable
    data class FriendsGetRequestsExtendedRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<FriendsRequestsXtrMessage>,
        @SerialName("count_unread") val countUnread: Int? = null,
        @SerialName("last_viewed") val lastViewed: Int? = null,
    )
}

