package ru.krindra.vknorthtypes.types.friends

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class FriendsGetResponse (
    val response: FriendsGetRawResponse
) {
    /**
     *
     * @param count Total friends number
     * @param items 
     */
    @Serializable
    data class FriendsGetRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<Int>,
    )
}

