package ru.krindra.vknorthtypes.types.friends

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class FriendsFriendExtendedStatus (
    @SerialName("sign") val sign: String? = null,
    @SerialName("is_request_unread") val isRequestUnread: Boolean? = null,
    @SerialName("friend_status") val friendStatus: FriendsFriendStatusStatus,
    @SerialName("user_id") val userId: Long,
)
