package ru.krindra.vknorthtypes.types.docs

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseUploadServer


typealias DocsGetUploadServerRawResponse = BaseUploadServer
@Serializable
data class DocsGetUploadServerResponse (
    val response: DocsGetUploadServerRawResponse
)

