package ru.krindra.vknorthtypes.types.docs

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class DocsGetResponse (
    val response: DocsGetRawResponse
) {
    @Serializable
    data class DocsGetRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<DocsDoc>,
    )
}

