package ru.krindra.vknorthtypes.types.podcast

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class PodcastExternalData (
    @SerialName("cover") val cover: PodcastCover? = null,
    @SerialName("title") val title: String? = null,
    @SerialName("owner_name") val ownerName: String? = null,
    @SerialName("owner_url") val ownerUrl: String? = null,
    @SerialName("url") val url: String? = null,
)
