package ru.krindra.vknorthtypes.types.podcast

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.photos.PhotosPhotoSizes

@Serializable
data class PodcastCover (
    @SerialName("sizes") val sizes: List<PhotosPhotoSizes>? = null,
)
