package ru.krindra.vknorthtypes.types.storage

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias StorageGetKeysRawResponse = List<String>
@Serializable
data class StorageGetKeysResponse (
    val response: StorageGetKeysRawResponse
)

