package ru.krindra.vknorthtypes.types.likes

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseBoolInt


@Serializable
data class LikesIsLikedResponse (
    val response: LikesIsLikedRawResponse
) {
    /**
     *
     * @param liked Information whether user liked the object
     * @param copied Information whether user reposted the object
     */
    @Serializable
    data class LikesIsLikedRawResponse (
        @SerialName("liked") val liked: BaseBoolInt,
        @SerialName("copied") val copied: BaseBoolInt,
    )
}

