package ru.krindra.vknorthtypes.types.widgets

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class WidgetsGetCommentsResponse (
    val response: WidgetsGetCommentsRawResponse
) {
    /**
     *
     * @param count Total number
     * @param posts 
     */
    @Serializable
    data class WidgetsGetCommentsRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("posts") val posts: List<WidgetsWidgetComment>,
    )
}

