package ru.krindra.vknorthtypes.types.widgets

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.users.UsersUserFull

@Serializable
data class WidgetsCommentRepliesItem (
    @SerialName("user") val user: UsersUserFull? = null,
    @SerialName("date") val date: Int? = null,
    @SerialName("uid") val uid: Long? = null,
    @SerialName("likes") val likes: WidgetsWidgetLikes? = null,
    @SerialName("cid") val cid: Long? = null,
    @SerialName("text") val text: String? = null,
)
