package ru.krindra.vknorthtypes.types.link

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class LinkTargetObject (
    @SerialName("item_id") val itemId: Long? = null,
    @SerialName("type") val type: String? = null,
    @SerialName("owner_id") val ownerId: Long? = null,
)
