package ru.krindra.vknorthtypes.types.bugtracker

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param userId 
 * @param companyId 
 * @param role 
 * @param roleName 
 * @param ts 
 * @param groupsCount 
 * @param productsCount 
 * @param reporterUrl 
 * @param groups 
 * @param products 
 */
@Serializable
data class BugtrackerCompanyMember (
    @SerialName("reporter_url") val reporterUrl: String,
    @SerialName("groups") val groups: List<Int>? = null,
    @SerialName("company_id") val companyId: Long,
    @SerialName("groups_count") val groupsCount: Int,
    @SerialName("products_count") val productsCount: Int,
    @SerialName("ts") val ts: Int,
    @SerialName("user_id") val userId: Long,
    @SerialName("role_name") val roleName: String,
    @SerialName("role") val role: Int,
    @SerialName("products") val products: List<BugtrackerCompanyMemberProduct>? = null,
)
