package ru.krindra.vknorthtypes.types.bugtracker

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class BugtrackerAddCompanyMembersResponse (
    val response: BugtrackerAddCompanyMembersRawResponse
) {
    /**
     *
     * @param errors 
     */
    @Serializable
    data class BugtrackerAddCompanyMembersRawResponse (
        @SerialName("errors") val errors: List<String>,
    )
}

