package ru.krindra.vknorthtypes.types.bugtracker

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param id 
 * @param title 
 * @param photoUrl 
 * @param access 
 * @param status 
 * @param licenceStatusText 
 */
@Serializable
data class BugtrackerCompanyMemberProduct (
    @SerialName("access") val access: Int,
    @SerialName("photo_url") val photoUrl: String? = null,
    @SerialName("licence_status_text") val licenceStatusText: String? = null,
    @SerialName("id") val id: Long,
    @SerialName("title") val title: String? = null,
    @SerialName("status") val status: Int,
)
