package ru.krindra.vknorthtypes.types.bugtracker

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.users.UsersUserFull


@Serializable
data class BugtrackerGetCompanyMembersResponse (
    val response: BugtrackerGetCompanyMembersRawResponse
) {
    /**
     *
     * @param companyMembers 
     * @param count 
     * @param profiles 
     */
    @Serializable
    data class BugtrackerGetCompanyMembersRawResponse (
        @SerialName("company_members") val companyMembers: List<BugtrackerCompanyMember>,
        @SerialName("count") val count: Int,
        @SerialName("profiles") val profiles: List<UsersUserFull>? = null,
    )
}

