package ru.krindra.vknorthtypes.types.bugtracker

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.photos.PhotosPhoto
import ru.krindra.vknorthtypes.types.docs.DocsDoc

@Serializable
data class BugtrackerAttachment (
    @SerialName("type") val type: String,
    @SerialName("doc") val doc: DocsDoc? = null,
    @SerialName("photo") val photo: PhotosPhoto? = null,
)
