package ru.krindra.vknorthtypes.types.bugtracker

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class BugtrackerBugreportSubscribeState (
    @SerialName("is_subscribed") val isSubscribed: Boolean? = null,
    @SerialName("can_set_subscribe") val canSetSubscribe: Boolean,
    @SerialName("set_subscribe_hash") val setSubscribeHash: String? = null,
)
