package ru.krindra.vknorthtypes.types.market

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.photos.PhotosPhoto
import ru.krindra.vknorthtypes.types.base.BaseRepostsInfo
import ru.krindra.vknorthtypes.types.base.BaseLink
import ru.krindra.vknorthtypes.types.base.BaseBoolInt
import ru.krindra.vknorthtypes.types.base.BaseLikes

@Serializable
data class MarketMarketItemFull (
    @SerialName("reposts") val reposts: BaseRepostsInfo? = null,
    @SerialName("price") val price: MarketPrice,
    @SerialName("is_owner") val isOwner: Boolean? = null,
    @SerialName("variants_grouping_id") val variantsGroupingId: Long? = null,
    @SerialName("date") val date: Int? = null,
    @SerialName("can_comment") val canComment: BaseBoolInt? = null,
    @SerialName("rating") val rating: Double? = null,
    @SerialName("orders_count") val ordersCount: Int? = null,
    @SerialName("title") val title: String,
    @SerialName("can_edit") val canEdit: Boolean? = null,
    @SerialName("promotion") val promotion: MarketItemPromotionInfo? = null,
    @SerialName("can_show_convert_to_service") val canShowConvertToService: Boolean? = null,
    @SerialName("owner_info") val ownerInfo: MarketItemOwnerInfo? = null,
    @SerialName("is_main_variant") val isMainVariant: Boolean? = null,
    @SerialName("cancel_info") val cancelInfo: BaseLink? = null,
    @SerialName("category_v2") val categoryV2: MarketMarketCategory? = null,
    @SerialName("access_key") val accessKey: String? = null,
    @SerialName("sku") val sku: String? = null,
    @SerialName("button_title") val buttonTitle: String? = null,
    @SerialName("is_adult") val isAdult: Boolean? = null,
    @SerialName("url") val url: String? = null,
    @SerialName("wishlist_item_id") val wishlistItemId: Long? = null,
    @SerialName("description") val description: String,
    @SerialName("post_id") val postId: Long? = null,
    @SerialName("stock_amount") val stockAmount: Int? = null,
    @SerialName("ad_id") val adId: Long? = null,
    @SerialName("owner_id") val ownerId: Long,
    @SerialName("vk_pay_discount") val vkPayDiscount: Int? = null,
    @SerialName("can_repost") val canRepost: BaseBoolInt? = null,
    @SerialName("category") val category: MarketMarketCategory,
    @SerialName("photos") val photos: List<PhotosPhoto>? = null,
    @SerialName("likes") val likes: BaseLikes? = null,
    @SerialName("user_agreement_info") val userAgreementInfo: String? = null,
    @SerialName("external_id") val externalId: String? = null,
    @SerialName("can_delete") val canDelete: Boolean? = null,
    @SerialName("id") val id: Long,
    @SerialName("is_favorite") val isFavorite: Boolean? = null,
    @SerialName("albums_ids") val albumsIds: List<Int>? = null,
    @SerialName("thumb_photo") val thumbPhoto: String? = null,
    @SerialName("post_owner_id") val postOwnerId: Long? = null,
    @SerialName("availability") val availability: MarketMarketItemAvailability,
    @SerialName("views_count") val viewsCount: Int? = null,
)
