package ru.krindra.vknorthtypes.types.market

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MarketGetCategoriesNewResponse (
    val response: MarketGetCategoriesNewRawResponse
) {
    /**
     *
     * @param items 
     */
    @Serializable
    data class MarketGetCategoriesNewRawResponse (
        @SerialName("items") val items: List<MarketMarketCategoryTree>,
    )
}

