package ru.krindra.vknorthtypes.types.market

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MarketGetOrderByIdResponse (
    val response: MarketGetOrderByIdRawResponse
) {
    /**
     *
     * @param order 
     */
    @Serializable
    data class MarketGetOrderByIdRawResponse (
        @SerialName("order") val order: MarketOrder? = null,
    )
}

