package ru.krindra.vknorthtypes.types.market

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
enum class MarketOwnerType(val value: String){
    @SerialName("base") BASE("base"),
    @SerialName("pro") PRO("pro"),
    @SerialName("disabled") DISABLED("disabled"),
}
