package ru.krindra.vknorthtypes.types.market

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MarketMarketItemBasic (
    @SerialName("id") val id: Long,
    @SerialName("price") val price: MarketPrice,
    @SerialName("owner_id") val ownerId: Long,
    @SerialName("is_favorite") val isFavorite: Boolean? = null,
    @SerialName("title") val title: String,
    @SerialName("thumb_photo") val thumbPhoto: String? = null,
)
