package ru.krindra.vknorthtypes.types.market

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.groups.GroupsGroupFull

import ru.krindra.vknorthtypes.types.wall.WallWallComment

import ru.krindra.vknorthtypes.types.users.UsersUserFull


@Serializable
data class MarketGetCommentsResponse (
    val response: MarketGetCommentsRawResponse
) {
    @Serializable
    data class MarketGetCommentsRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<WallWallComment>,
        @SerialName("profiles") val profiles: List<UsersUserFull>? = null,
        @SerialName("groups") val groups: List<GroupsGroupFull>? = null,
    )
}

