package ru.krindra.vknorthtypes.types.market

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MarketMarketCategoryNested (
    @SerialName("parent") val parent: MarketMarketCategoryNested? = null,
    @SerialName("id") val id: Long,
    @SerialName("name") val name: String,
    @SerialName("is_v2") val isV2: Boolean? = null,
)
