package ru.krindra.vknorthtypes.types.market

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias MarketCreateCommentRawResponse = Int
/**
 *
 * Comment ID
 * 
 */
@Serializable
data class MarketCreateCommentResponse (
    val response: MarketCreateCommentRawResponse
)

