package ru.krindra.vknorthtypes.types.market

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param id Currency ID
 * @param name Currency sign
 * @param title Currency title
 */
@Serializable
data class MarketCurrency (
    @SerialName("title") val title: String,
    @SerialName("name") val name: String,
    @SerialName("id") val id: Long,
)
