package ru.krindra.vknorthtypes.types.market

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MarketMarketCategoryTreeView (
    @SerialName("selected") val selected: Boolean? = null,
    @SerialName("type") val type: String? = null,
    @SerialName("root_path") val rootPath: List<String>? = null,
)
