package ru.krindra.vknorthtypes.types.market

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MarketMarketItem (
    @SerialName("price") val price: MarketPrice,
    @SerialName("is_owner") val isOwner: Boolean? = null,
    @SerialName("variants_grouping_id") val variantsGroupingId: Long? = null,
    @SerialName("date") val date: Int? = null,
    @SerialName("title") val title: String,
    @SerialName("is_main_variant") val isMainVariant: Boolean? = null,
    @SerialName("category_v2") val categoryV2: MarketMarketCategory? = null,
    @SerialName("access_key") val accessKey: String? = null,
    @SerialName("sku") val sku: String? = null,
    @SerialName("button_title") val buttonTitle: String? = null,
    @SerialName("is_adult") val isAdult: Boolean? = null,
    @SerialName("url") val url: String? = null,
    @SerialName("description") val description: String,
    @SerialName("post_id") val postId: Long? = null,
    @SerialName("stock_amount") val stockAmount: Int? = null,
    @SerialName("owner_id") val ownerId: Long,
    @SerialName("category") val category: MarketMarketCategory,
    @SerialName("external_id") val externalId: String? = null,
    @SerialName("id") val id: Long,
    @SerialName("is_favorite") val isFavorite: Boolean? = null,
    @SerialName("thumb_photo") val thumbPhoto: String? = null,
    @SerialName("post_owner_id") val postOwnerId: Long? = null,
    @SerialName("availability") val availability: MarketMarketItemAvailability,
)
