package ru.krindra.vknorthtypes.types.market

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class MarketGetAlbumsResponse (
    val response: MarketGetAlbumsRawResponse
) {
    @Serializable
    data class MarketGetAlbumsRawResponse (
        @SerialName("count") val count: Int,
        @SerialName("items") val items: List<MarketMarketAlbum>,
    )
}

