package ru.krindra.vknorthtypes.types.market

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseImage

@Serializable
data class MarketItemOwnerInfo (
    @SerialName("name") val name: String? = null,
    @SerialName("is_corporated_market") val isCorporatedMarket: Boolean? = null,
    @SerialName("category_url") val categoryUrl: String? = null,
    @SerialName("market_type") val marketType: MarketOwnerType? = null,
    @SerialName("avatar") val avatar: List<BaseImage>? = null,
    @SerialName("category") val category: String? = null,
)
