package ru.krindra.vknorthtypes.types.asr

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AsrProcessResponse (
    val response: AsrProcessRawResponse
) {
    /**
     *
     * @param taskId ID of created task in UUID format.
     */
    @Serializable
    data class AsrProcessRawResponse (
        @SerialName("task_id") val taskId: String,
    )
}

