package ru.krindra.vknorthtypes.types.stories

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.photos.PhotosPhoto
import ru.krindra.vknorthtypes.types.base.BaseBoolInt
import ru.krindra.vknorthtypes.types.video.VideoVideoFull

@Serializable
data class StoriesStory (
    @SerialName("can_ask") val canAsk: BaseBoolInt? = null,
    @SerialName("is_deleted") val isDeleted: Boolean? = null,
    @SerialName("photo") val photo: PhotosPhoto? = null,
    @SerialName("narratives_count") val narrativesCount: Int? = null,
    @SerialName("date") val date: Int? = null,
    @SerialName("can_comment") val canComment: BaseBoolInt? = null,
    @SerialName("replies") val replies: StoriesReplies? = null,
    @SerialName("video") val video: VideoVideoFull? = null,
    @SerialName("access_key") val accessKey: String? = null,
    @SerialName("can_like") val canLike: Boolean? = null,
    @SerialName("can_ask_anonymous") val canAskAnonymous: BaseBoolInt? = null,
    @SerialName("can_share") val canShare: BaseBoolInt? = null,
    @SerialName("parent_story") val parentStory: StoriesStory? = null,
    @SerialName("link") val link: StoriesStoryLink? = null,
    @SerialName("parent_story_access_key") val parentStoryAccessKey: String? = null,
    @SerialName("can_hide") val canHide: BaseBoolInt? = null,
    @SerialName("is_expired") val isExpired: Boolean? = null,
    @SerialName("parent_story_id") val parentStoryId: Long? = null,
    @SerialName("first_narrative_title") val firstNarrativeTitle: String? = null,
    @SerialName("can_see") val canSee: BaseBoolInt? = null,
    @SerialName("owner_id") val ownerId: Long,
    @SerialName("views") val views: Int? = null,
    @SerialName("seen") val seen: BaseBoolInt? = null,
    @SerialName("parent_story_owner_id") val parentStoryOwnerId: Long? = null,
    @SerialName("clickable_stickers") val clickableStickers: StoriesClickableStickers? = null,
    @SerialName("can_use_in_narrative") val canUseInNarrative: Boolean? = null,
    @SerialName("id") val id: Long,
    @SerialName("can_reply") val canReply: BaseBoolInt? = null,
    @SerialName("expires_at") val expiresAt: Int? = null,
    @SerialName("type") val type: StoriesStoryType? = null,
)
