package ru.krindra.vknorthtypes.types.stories

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class StoriesGetVideoUploadServerResponse (
    val response: StoriesGetVideoUploadServerRawResponse
) {
    /**
     *
     * @param uploadUrl Upload URL
     * @param userIds Users ID who can to see story.
     */
    @Serializable
    data class StoriesGetVideoUploadServerRawResponse (
        @SerialName("upload_url") val uploadUrl: String,
        @SerialName("user_ids") val userIds: List<Int>,
    )
}

