package ru.krindra.vknorthtypes.types.stories

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param count Stat value
 * @param state 
 */
@Serializable
data class StoriesStoryStatsStat (
    @SerialName("state") val state: StoriesStoryStatsState,
    @SerialName("count") val count: Int? = null,
)
