package ru.krindra.vknorthtypes.types.stories

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class StoriesStoryLink (
    @SerialName("url") val url: String,
    @SerialName("link_url_target") val linkUrlTarget: String? = null,
    @SerialName("text") val text: String,
)
