package ru.krindra.vknorthtypes.types.stories

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param count Replies number.
 * @param new New replies number.
 */
@Serializable
data class StoriesReplies (
    @SerialName("new") val new: Int? = null,
    @SerialName("count") val count: Int,
)
