package ru.krindra.vknorthtypes.types.stories

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class StoriesClickableStickers (
    @SerialName("original_width") val originalWidth: Int,
    @SerialName("clickable_stickers") val clickableStickers: List<StoriesClickableSticker>,
    @SerialName("original_height") val originalHeight: Int,
)
