package ru.krindra.vknorthtypes.types.stories

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param header 
 * @param lines 
 */
@Serializable
data class StoriesStatCategory (
    @SerialName("header") val header: String,
    @SerialName("lines") val lines: List<StoriesStatLine>,
)
