package ru.krindra.vknorthtypes.types.stories

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.users.UsersUserFull

@Serializable
data class StoriesViewersItem (
    @SerialName("user") val user: UsersUserFull? = null,
    @SerialName("is_liked") val isLiked: Boolean,
    @SerialName("user_id") val userId: Long,
)
