package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AdsAddOfficeUsersRawResponse = List<Boolean>
@Serializable
data class AdsAddOfficeUsersResponse (
    val response: AdsAddOfficeUsersRawResponse
)

