package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AdsCampaign (
    @SerialName("id") val id: Long,
    @SerialName("user_goal_type") val userGoalType: Int? = null,
    @SerialName("is_cbo_enabled") val isCboEnabled: Boolean? = null,
    @SerialName("name") val name: String,
    @SerialName("views_limit") val viewsLimit: Int? = null,
    @SerialName("day_limit") val dayLimit: String,
    @SerialName("status") val status: AdsCampaignStatus,
    @SerialName("type") val type: AdsCampaignType,
    @SerialName("goal_type") val goalType: Int? = null,
    @SerialName("all_limit") val allLimit: String,
    @SerialName("stop_time") val stopTime: Int,
    @SerialName("update_time") val updateTime: Int? = null,
    @SerialName("create_time") val createTime: Int? = null,
    @SerialName("start_time") val startTime: Int,
    @SerialName("ads_count") val adsCount: Int? = null,
)
