package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AdsClipItem (
    @SerialName("link") val link: AdsClipItemLink? = null,
    @SerialName("video_id") val videoId: Long? = null,
    @SerialName("preview_url") val previewUrl: String? = null,
)
