package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AdsCreateTargetGroupResponse (
    val response: AdsCreateTargetGroupRawResponse
) {
    /**
     *
     * @param id Group ID
     * @param pixel Pixel code
     */
    @Serializable
    data class AdsCreateTargetGroupRawResponse (
        @SerialName("id") val id: Long? = null,
        @SerialName("pixel") val pixel: String? = null,
    )
}

