package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AdsDeleteCampaignsRawResponse = List<Int>
@Serializable
data class AdsDeleteCampaignsResponse (
    val response: AdsDeleteCampaignsRawResponse
)

