package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AdsDeleteAdsRawResponse = List<Int>
@Serializable
data class AdsDeleteAdsResponse (
    val response: AdsDeleteAdsRawResponse
)

