package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AdsDemostatsFormat (
    @SerialName("month") val month: String? = null,
    @SerialName("age") val age: List<AdsStatsAge>? = null,
    @SerialName("sex") val sex: List<AdsStatsSex>? = null,
    @SerialName("day_from") val dayFrom: String? = null,
    @SerialName("day") val day: String? = null,
    @SerialName("day_to") val dayTo: String? = null,
    @SerialName("overall") val overall: Int? = null,
    @SerialName("cities") val cities: List<AdsStatsCities>? = null,
    @SerialName("sex_age") val sexAge: List<AdsStatsSexAge>? = null,
)
