package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AdsFloodStats (
    @SerialName("left") val left: Int,
    @SerialName("stats_by_user") val statsByUser: List<AdsFloodStatsByUserItem>? = null,
    @SerialName("refresh") val refresh: Int,
)
