package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AdsGetFloodStatsRawResponse = AdsFloodStats
@Serializable
data class AdsGetFloodStatsResponse (
    val response: AdsGetFloodStatsRawResponse
)

