package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AdsGetOfficeUsersRawResponse = List<AdsUsers>
@Serializable
data class AdsGetOfficeUsersResponse (
    val response: AdsGetOfficeUsersRawResponse
)

