package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AdsGetBudgetRawResponse = String
@Serializable()
data class AdsGetBudgetResponse (
    val response: AdsGetBudgetRawResponse
)

