package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AdsGetAdsLayoutRawResponse = List<AdsAdLayout>
@Serializable
data class AdsGetAdsLayoutResponse (
    val response: AdsGetAdsLayoutRawResponse
)

