package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AdsGetSuggestionsRawResponse = List<AdsTargSuggestions>
@Serializable
data class AdsGetSuggestionsResponse (
    val response: AdsGetSuggestionsRawResponse
)

