package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AdsGetVideoUploadURLRawResponse = String
/**
 *
 * Video upload URL
 * 
 */
@Serializable
data class AdsGetVideoUploadURLResponse (
    val response: AdsGetVideoUploadURLRawResponse
)

