package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param description Reject reason
 * @param redirectUrl URL
 * @param status Link status
 */
@Serializable
data class AdsLinkStatus (
    @SerialName("status") val status: String,
    @SerialName("redirect_url") val redirectUrl: String? = null,
    @SerialName("description") val description: String? = null,
)
