package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param clientType 
 * @param clientName 
 * @param inn 
 * @param phone 
 * @param subagent 
 * @param contractNumber 
 * @param contractDate 
 * @param contractType 
 * @param contractObject 
 * @param withVat 
 */
@Serializable
data class AdsOrdData (
    @SerialName("client_name") val clientName: String,
    @SerialName("contract_number") val contractNumber: String,
    @SerialName("contract_date") val contractDate: String,
    @SerialName("with_vat") val withVat: Boolean,
    @SerialName("client_type") val clientType: AdsOrdClientType,
    @SerialName("contract_type") val contractType: String,
    @SerialName("contract_object") val contractObject: String,
    @SerialName("inn") val inn: String? = null,
    @SerialName("phone") val phone: String,
    @SerialName("subagent") val subagent: AdsOrdSubagent? = null,
)
