package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param type 
 * @param name 
 * @param inn 
 * @param phone 
 */
@Serializable
data class AdsOrdSubagent (
    @SerialName("name") val name: String,
    @SerialName("inn") val inn: String? = null,
    @SerialName("phone") val phone: String,
    @SerialName("type") val type: AdsOrdClientType,
)
