package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.wall.WallWallpostAttachment

@Serializable
data class AdsPost (
    @SerialName("date") val date: Int? = null,
    @SerialName("likes") val likes: AdsPostLikes? = null,
    @SerialName("can_delete") val canDelete: Int? = null,
    @SerialName("created_by") val createdBy: Int? = null,
    @SerialName("from_id") val fromId: Long? = null,
    @SerialName("can_edit") val canEdit: Int? = null,
    @SerialName("donut") val donut: AdsPostDonut? = null,
    @SerialName("id") val id: Long? = null,
    @SerialName("is_pinned") val isPinned: Int? = null,
    @SerialName("text") val text: String? = null,
    @SerialName("reposts") val reposts: AdsPostReposts? = null,
    @SerialName("views") val views: AdsPostViews? = null,
    @SerialName("marked_as_ads") val markedAsAds: Int? = null,
    @SerialName("owner") val owner: AdsPostOwner? = null,
    @SerialName("carousel_offset") val carouselOffset: Int? = null,
    @SerialName("type") val type: String? = null,
    @SerialName("edited") val edited: Int? = null,
    @SerialName("hash") val hash: String? = null,
    @SerialName("can_pin") val canPin: Int? = null,
    @SerialName("short_text_rate") val shortTextRate: Double? = null,
    @SerialName("is_favorite") val isFavorite: Boolean? = null,
    @SerialName("comments") val comments: AdsPostComments? = null,
    @SerialName("ads_easy_promote") val adsEasyPromote: AdsPostEasyPromote? = null,
    @SerialName("owner_id") val ownerId: Long? = null,
    @SerialName("post_type") val postType: String? = null,
    @SerialName("is_promoted_post_stealth") val isPromotedPostStealth: Boolean? = null,
    @SerialName("attachments") val attachments: List<WallWallpostAttachment>? = null,
)
