package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AdsPostEasyPromote (
    @SerialName("button_text") val buttonText: String? = null,
    @SerialName("label_text") val labelText: String? = null,
    @SerialName("type") val type: Int? = null,
    @SerialName("ad_id") val adId: Long? = null,
    @SerialName("is_ad_not_easy") val isAdNotEasy: Boolean? = null,
    @SerialName("top_union_id") val topUnionId: Long? = null,
    @SerialName("text") val text: String? = null,
)
