package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AdsRules (
    @SerialName("help_label") val helpLabel: String? = null,
    @SerialName("help_url") val helpUrl: AdsRulesHelpUrl? = null,
    @SerialName("content_html") val contentHtml: String? = null,
    @SerialName("help_chat") val helpChat: Boolean? = null,
)
