package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AdsRemoveOfficeUsersRawResponse = List<Boolean>
@Serializable
data class AdsRemoveOfficeUsersResponse (
    val response: AdsRemoveOfficeUsersRawResponse
)

