package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AdsShareTargetGroupResponse (
    val response: AdsShareTargetGroupRawResponse
) {
    /**
     *
     * @param id Group ID
     */
    @Serializable
    data class AdsShareTargetGroupRawResponse (
        @SerialName("id") val id: Long,
    )
}

