package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AdsSaveLookalikeRequestResultResponse (
    val response: AdsSaveLookalikeRequestResultRawResponse
) {
    /**
     *
     * @param retargetingGroupId Retargeting group ID
     * @param audienceCount Audience count
     */
    @Serializable
    data class AdsSaveLookalikeRequestResultRawResponse (
        @SerialName("retargeting_group_id") val retargetingGroupId: Long,
        @SerialName("audience_count") val audienceCount: Int,
    )
}

