package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

/**
 *
 * @param targetPixelId 
 * @param name 
 * @param domain 
 * @param categoryId 
 * @param lastUpdated 
 * @param pixel 
 */
@Serializable
data class AdsTargetPixelInfo (
    @SerialName("target_pixel_id") val targetPixelId: Long,
    @SerialName("name") val name: String,
    @SerialName("domain") val domain: String,
    @SerialName("last_updated") val lastUpdated: Int,
    @SerialName("category_id") val categoryId: Long,
    @SerialName("pixel") val pixel: String,
)
