package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable

@Serializable
data class AdsUpdateAdsStatus (
    @SerialName("id") val id: Long,
    @SerialName("error_desc") val errorDesc: String? = null,
    @SerialName("error_code") val errorCode: Int? = null,
)
