package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import ru.krindra.vknorthtypes.types.base.BaseError

/**
 *
 * @param userId 
 * @param isSuccess 
 * @param error 
 */
@Serializable
data class AdsUpdateOfficeUsersResult (
    @SerialName("is_success") val isSuccess: Boolean,
    @SerialName("user_id") val userId: Long,
    @SerialName("error") val error: BaseError? = null,
)
