package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AdsUpdateAdsRawResponse = List<AdsUpdateAdsStatus>
@Serializable
data class AdsUpdateAdsResponse (
    val response: AdsUpdateAdsRawResponse
)

