package ru.krindra.vknorthtypes.types.ads

// **********
// THIS FILE IS AUTOGENERATED!!! DO NOT EDIT IT!!!
// **********
import kotlinx.serialization.Serializable

typealias AdsUpdateCampaignsRawResponse = List<AdsCreateCampaignStatus>
@Serializable
data class AdsUpdateCampaignsResponse (
    val response: AdsUpdateCampaignsRawResponse
)

